import { ChipVolatileBaseApy } from '@/dex/components/ChipVolatileBaseApy'
import { LARGE_APY } from '@/dex/constants'
import Box from '@mui/material/Box'
import Typography, { type TypographyProps } from '@mui/material/Typography'
import type { CellContext } from '@tanstack/react-table'
import { t } from '@ui-kit/lib/i18n'
import { Tooltip, type TooltipProps } from '@ui-kit/shared/ui/Tooltip'
import { TooltipDescription, TooltipItem, TooltipItems, TooltipWrapper } from '@ui-kit/shared/ui/TooltipComponents'
import { SizesAndSpaces } from '@ui-kit/themes/design/1_sizes_spaces'
import { formatNumber } from '@ui-kit/utils'
import type { PoolRow } from '../types'
import { aprToPoolApy } from './utils'

const { Spacing } = SizesAndSpaces

const formatApy = (apy: number | null | undefined) => formatNumber(apy || null, 'percent.rate')

const BaseApyAmount = ({
  baseDailyApr,
  typographyVariant,
}: {
  baseDailyApr: PoolRow['baseDailyApr']
  typographyVariant: TypographyProps['variant']
}) => (
  <Typography component="span" variant={typographyVariant}>
    {formatApy(aprToPoolApy(baseDailyApr))}
  </Typography>
)

const BaseApyTooltipBody = ({ baseDailyApr, baseWeeklyApr }: Pick<PoolRow, 'baseDailyApr' | 'baseWeeklyApr'>) => {
  const baseDailyApy = aprToPoolApy(baseDailyApr)
  const baseWeeklyApy = aprToPoolApy(baseWeeklyApr)

  return (
    <Box>
      <Typography variant="bodyXsRegular" color="textTertiary" sx={{ marginBottom: Spacing.xs }}>
        {t`(annualized)`}
      </Typography>
      <Box component="ul" sx={{ margin: 0, paddingInlineStart: Spacing.md }}>
        <Typography component="li" variant="bodySRegular">
          {t`Daily`}: {formatNumber(baseDailyApy === 0 ? null : baseDailyApy, 'percent.value')}
        </Typography>
        <Typography component="li" variant="bodySRegular">
          {t`Weekly`}: {formatNumber(baseWeeklyApy === 0 ? null : baseWeeklyApy, 'percent.value')}
        </Typography>
      </Box>

      {baseDailyApy != null && baseDailyApy < 0 && (
        <Typography variant="bodySRegular" color="warning" sx={{ marginTop: Spacing.sm }}>
          {t`Base vAPY can temporarily be negative when A parameter is ramped down, or crypto pools spend profit to rebalance.`}
        </Typography>
      )}
    </Box>
  )
}

const BaseApyTooltipContent = ({ baseDailyApr, baseWeeklyApr }: Pick<PoolRow, 'baseDailyApr' | 'baseWeeklyApr'>) => {
  const baseDailyApy = aprToPoolApy(baseDailyApr)
  const baseWeeklyApy = aprToPoolApy(baseWeeklyApr)

  return (
    <Box data-testid="pool-base-apy-tooltip-content">
      <TooltipWrapper>
        <TooltipDescription
          text={t`Annualized yield generated by the pool, shown using daily and weekly measurement windows. If the pool contains yield-bearing assets, their intrinsic yield is included.`}
        />
        <TooltipItems secondary>
          <TooltipItem variant="independent" title={t`Daily`}>
            {formatApy(baseDailyApy)}
          </TooltipItem>
          <TooltipItem variant="independent" title={t`Weekly`}>
            {formatApy(baseWeeklyApy)}
          </TooltipItem>
        </TooltipItems>
        {baseDailyApy != null && baseDailyApy < 0 && (
          <Typography variant="bodySRegular" color="warning">
            {t`Base vAPY can temporarily be negative when A parameter is ramped down, or crypto pools spend profit to rebalance.`}
          </Typography>
        )}
      </TooltipWrapper>
    </Box>
  )
}

export const BaseApyValue = ({
  pool,
  textAlign = 'end',
  tooltipPlacement,
  typographyVariant = 'tableCellMBold',
}: {
  pool: PoolRow
  textAlign?: 'start' | 'end'
  tooltipPlacement?: TooltipProps['placement']
  typographyVariant?: TypographyProps['variant']
}) => {
  const baseDailyApy = aprToPoolApy(pool.baseDailyApr)
  const content = <BaseApyAmount baseDailyApr={pool.baseDailyApr} typographyVariant={typographyVariant} />

  return (
    <Box data-testid="pool-base-apy-value" sx={{ display: 'flex', justifyContent: textAlign }}>
      {baseDailyApy != null && baseDailyApy > LARGE_APY ? (
        <ChipVolatileBaseApy />
      ) : pool.baseDailyApr == null ? (
        content
      ) : (
        <Tooltip
          title={t`Pool APY`}
          body={<BaseApyTooltipBody baseDailyApr={pool.baseDailyApr} baseWeeklyApr={pool.baseWeeklyApr} />}
          placement={tooltipPlacement}
        >
          {content}
        </Tooltip>
      )}
    </Box>
  )
}

export const BaseApyCell = ({ row: { original: pool } }: CellContext<PoolRow, PoolRow['baseDailyApr']>) => {
  const baseDailyApy = aprToPoolApy(pool.baseDailyApr)

  if (pool.baseDailyApr == null || (baseDailyApy != null && baseDailyApy > LARGE_APY)) {
    return <BaseApyValue pool={pool} />
  }

  return (
    <Box data-testid="pool-base-apy-value" sx={{ display: 'flex', justifyContent: 'end' }}>
      <Tooltip
        clickable
        title={t`Base APY`}
        body={<BaseApyTooltipContent baseDailyApr={pool.baseDailyApr} baseWeeklyApr={pool.baseWeeklyApr} />}
        placement="top"
      >
        <Box component="span" data-testid="pool-base-apy-tooltip-trigger" sx={{ display: 'inline-flex' }}>
          <BaseApyAmount baseDailyApr={pool.baseDailyApr} typographyVariant="tableCellMBold" />
        </Box>
      </Tooltip>
    </Box>
  )
}
