# configuration options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - /
      - /apps/main/
      - /packages/curve-ui-kit/
      - /packages/prices-api/
      - /packages/ui/
      - /packages/external-rewards/
      - /tests/
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 4 # avoid new packages that could have chain attack vulnerabilities
    ignore:
      - dependency-name: zustand
        update-types: ['version-update:semver-major']
      - dependency-name: '@curvefi/*' # curve updates done manually
    groups:
      # Group all minor updates in a single PR
      minor-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 4 # avoid new packages that could have chain attack vulnerabilities
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
