approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 1440

npmPreapprovedPackages:
  - "@curvefi/llamalend-api"
  - "@curvefi/api"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
