approvedGitRepositories:
  - "**"
enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: 1440  # 1 day
npmPreapprovedPackages:
- "@curvefi/llamalend-api"
- "@curvefi/api"
yarnPath: .yarn/releases/yarn-4.15.0.cjs
