import { PoolColumnId } from '@/dex/features/pool-list/columns'
import { setupDexPoolListV2Mocks, V2_POOL_FIXTURES } from '@cy/support/helpers/dex-pool-list-v2-mocks'
import { DESKTOP_VIEWPORT, getV2PoolCell, visitV2PoolList } from '@cy/support/helpers/dex-pools-list-v2.helpers'
import { MAINNET_CRV_ADDRESS } from '@ui-kit/utils'

const POINTS_BADGE = '[data-testid="pool-points-badge"]'
const EXTRA_REWARD_BADGE = '[data-testid="pool-extra-reward-badge"]'
const CAMPAIGN_REWARD_BADGE = '[data-testid="pool-campaign-reward-badge"]'
const CRV_REWARD_BADGE = '[data-testid="pool-crv-reward-badge"]'
const REWARD_BADGES = [POINTS_BADGE, EXTRA_REWARD_BADGE, CAMPAIGN_REWARD_BADGE, CRV_REWARD_BADGE].join(',')
const TOOLTIP = '[role="tooltip"]'

const showWeeklyBaseApy = () => {
  cy.get('[data-testid="btn-visibility-settings"]').click()
  cy.get(`[data-testid="visibility-toggle-${PoolColumnId.WeeklyBaseApy}"]`).click()
  cy.get('body').click(0, 0)
}

describe('V2 pool-list yields', () => {
  beforeEach(() => {
    setupDexPoolListV2Mocks()
    visitV2PoolList({ viewport: DESKTOP_VIEWPORT })
  })

  it('combines the yield sources and exposes their detailed tooltips', () => {
    const { address } = V2_POOL_FIXTURES.showcase

    showWeeklyBaseApy()
    getV2PoolCell(address, PoolColumnId.NetApy).find('[data-testid="pool-net-apy"]').should('have.text', '20.70%')
    getV2PoolCell(address, PoolColumnId.BaseApy).should('contain.text', '10.51%')
    getV2PoolCell(address, PoolColumnId.WeeklyBaseApy).should('contain.text', '22.09%')
    getV2PoolCell(address, PoolColumnId.RewardsApy).should('contain.text', '5.06%')
    getV2PoolCell(address, PoolColumnId.GaugeApy).within(() => {
      cy.get('[data-testid="pool-gauge-apy-unboosted"]').should('have.text', '5.12%')
      cy.get('[data-testid="pool-gauge-apy-boosted"]').should('have.text', '13.30%')
      cy.get(`[data-testid="token-icon-${MAINNET_CRV_ADDRESS}"]`).should('have.length', 1)
    })

    getV2PoolCell(address, PoolColumnId.Points).within(() => {
      cy.get(POINTS_BADGE).should('have.length', 4)
      cy.contains(POINTS_BADGE, '30x').should('be.visible')
      cy.contains(POINTS_BADGE, '20x').should('be.visible')
      cy.contains(POINTS_BADGE, 'Points').should('be.visible')
    })

    getV2PoolCell(address, PoolColumnId.NetApy).within(() => {
      cy.get(POINTS_BADGE).should('have.length', 4).and('have.text', '')
      cy.get(REWARD_BADGES).should($badges => {
        expect([...$badges].map(badge => badge.dataset.testid)).to.deep.equal([
          'pool-points-badge',
          'pool-points-badge',
          'pool-points-badge',
          'pool-points-badge',
          'pool-extra-reward-badge',
          'pool-campaign-reward-badge',
          'pool-crv-reward-badge',
        ])
      })
    })
    getV2PoolCell(address, PoolColumnId.RewardsApy).within(() => {
      cy.get(POINTS_BADGE).should('not.exist')
      cy.get(EXTRA_REWARD_BADGE).should('have.length', 1)
      cy.get(CAMPAIGN_REWARD_BADGE).should('have.length', 1)
      cy.get(CRV_REWARD_BADGE).should('not.exist')
    })

    getV2PoolCell(address, PoolColumnId.NetApy)
      .find('[data-testid="pool-net-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP)
      .should('be.visible')
      .and('contain.text', 'Base APY')
      .and('contain.text', '10.51%')
      .and('contain.text', 'Incentives')
      .and('contain.text', '10.19%')
      .and('contain.text', 'Total APY')
      .and('contain.text', '20.70%')
      .and('contain.text', 'Max veCRV Boost (2.5x)')
      .and('contain.text', '13.30%')
      .and('contain.text', 'Total max veCRV APY')
      .and('contain.text', '28.87%')
      .and('contain.text', 'Points are shown for reference and are excluded from both totals.')
    cy.get(`${TOOLTIP} a[target="_blank"]`).should('have.length', 5)
    cy.get(`${TOOLTIP} a[href="https://app.termmax.ts.finance"]`).should('contain.text', '30x')
    cy.get(`${TOOLTIP} a[href="https://app.re.xyz/points"]`).should('contain.text', '20x')
    cy.get(`${TOOLTIP} a[href$="/v2-points-1"]`).should('have.text', '-')
    for (const platform of ['TermMax', 'Re', 'V2 points', 'V2 xp', 'V2 stars']) {
      cy.get(`${TOOLTIP} img[alt="${platform}"]`).should('have.length', 1)
    }
    getV2PoolCell(address, PoolColumnId.NetApy).find('[data-testid="pool-net-apy-tooltip-trigger"]').trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.BaseApy)
      .find('[data-testid="pool-base-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP)
      .should(
        'contain.text',
        'Annualized yield generated by the pool based on trading activity over the past 24 hours.',
      )
      .and('contain.text', 'intrinsic yield is included')
      .and('contain.text', 'Daily')
      .and('contain.text', '10.51%')
      .and('contain.text', 'Weekly')
      .and('contain.text', '22.09%')
    getV2PoolCell(address, PoolColumnId.BaseApy)
      .find('[data-testid="pool-base-apy-tooltip-trigger"]')
      .trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.RewardsApy)
      .find('[data-testid="pool-rewards-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'Incentives')
      .and('contain.text', '2.02%')
      .and('contain.text', 'Campaign rewards')
      .and('contain.text', '3.04%')
      .and('contain.text', 'Rewards APY')
      .and('contain.text', '5.06%')
      .and('contain.text', 'Points are not included.')
    getV2PoolCell(address, PoolColumnId.RewardsApy)
      .find('[data-testid="pool-rewards-apy-tooltip-trigger"]')
      .trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.GaugeApy)
      .find('[data-testid="pool-gauge-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'Gauge APY')
      .and('contain.text', 'Unboosted')
      .and('contain.text', '5.12%')
      .and('contain.text', 'Max boost')
      .and('contain.text', '13.30%')
      .and('contain.text', 'The maximum rate assumes the full 2.5x gauge boost.')
    cy.get(`${TOOLTIP} [data-testid="token-icon-${MAINNET_CRV_ADDRESS}"]`).should('have.length', 2)
    getV2PoolCell(address, PoolColumnId.GaugeApy)
      .find('[data-testid="pool-gauge-apy-tooltip-trigger"]')
      .trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.NetApy).find(POINTS_BADGE).first().trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'TermMax')
      .and('contain.text', 'Points for providing liquidity.')
      .and('contain.text', 'Go to issuer')
    getV2PoolCell(address, PoolColumnId.NetApy).find(POINTS_BADGE).first().trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.NetApy).find(EXTRA_REWARD_BADGE).trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'Extra pool reward')
      .and('contain.text', 'APY from an extra reward')
      .and('contain.text', 'APY: 2.02%')
    getV2PoolCell(address, PoolColumnId.NetApy).find(EXTRA_REWARD_BADGE).trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.NetApy).find(CAMPAIGN_REWARD_BADGE).trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'APY: 3.04%')
      .and('contain.text', 'Steps:')
      .and('contain.text', 'Go to issuer')
    getV2PoolCell(address, PoolColumnId.NetApy).find(CAMPAIGN_REWARD_BADGE).trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    getV2PoolCell(address, PoolColumnId.NetApy).find(CRV_REWARD_BADGE).trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'CRV gauge reward')
      .and('contain.text', '5.12%')
      .and('contain.text', '13.30%')
      .and('contain.text', 'max boost of 2.50')
  })

  it('handles inactive, incomplete, empty, and volatile yield data', () => {
    showWeeklyBaseApy()

    const killed = V2_POOL_FIXTURES.killed.address
    getV2PoolCell(killed, PoolColumnId.NetApy).should('contain.text', '6.07%')
    getV2PoolCell(killed, PoolColumnId.RewardsApy).should('contain.text', '5.06%')
    getV2PoolCell(killed, PoolColumnId.GaugeApy)
      .should('contain.text', 'Inactive gauge')
      .find(`[data-testid="token-icon-${MAINNET_CRV_ADDRESS}"]`)
      .should('not.exist')
    getV2PoolCell(killed, PoolColumnId.NetApy).within(() => {
      cy.get(POINTS_BADGE).should('exist')
      cy.get(EXTRA_REWARD_BADGE).should('exist')
      cy.get(CAMPAIGN_REWARD_BADGE).should('exist')
      cy.get(CRV_REWARD_BADGE).should('not.exist')
    })
    getV2PoolCell(killed, PoolColumnId.NetApy).find('[data-testid="pool-net-apy-tooltip-trigger"]').trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'Incentives')
      .and('contain.text', '5.06%')
      .and('contain.text', 'Total APY')
      .and('contain.text', '6.07%')
      .and('not.contain.text', 'Max veCRV Boost (2.5x)')
    cy.get(`${TOOLTIP} [data-testid="token-icon-${MAINNET_CRV_ADDRESS}"]`).should('not.exist')
    getV2PoolCell(killed, PoolColumnId.NetApy).find('[data-testid="pool-net-apy-tooltip-trigger"]').trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    const partial = V2_POOL_FIXTURES.partial.address
    getV2PoolCell(partial, PoolColumnId.NetApy).should('contain.text', '6.13%')
    getV2PoolCell(partial, PoolColumnId.GaugeApy)
      .should('have.text', '-')
      .find('[data-testid="pool-gauge-apy-tooltip-trigger"]')
      .should('not.exist')
    getV2PoolCell(partial, PoolColumnId.NetApy).find(CRV_REWARD_BADGE).should('not.exist')
    getV2PoolCell(partial, PoolColumnId.NetApy)
      .find('[data-testid="pool-net-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP)
      .should('contain.text', 'CRV')
      .and('contain.text', '5.12%')
      .and('contain.text', 'Total APY')
      .and('contain.text', '6.13%')
      .and('not.contain.text', 'Max veCRV Boost (2.5x)')
    getV2PoolCell(partial, PoolColumnId.NetApy).find('[data-testid="pool-net-apy-tooltip-trigger"]').trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    const empty = V2_POOL_FIXTURES.empty.address
    for (const column of [
      PoolColumnId.NetApy,
      PoolColumnId.BaseApy,
      PoolColumnId.WeeklyBaseApy,
      PoolColumnId.RewardsApy,
      PoolColumnId.GaugeApy,
      PoolColumnId.Points,
    ]) {
      getV2PoolCell(empty, column).should('have.text', '-').and('not.contain.text', '0%')
    }
    getV2PoolCell(empty, PoolColumnId.NetApy).find('[data-testid="pool-net-apy-tooltip-trigger"]').should('not.exist')
    getV2PoolCell(empty, PoolColumnId.RewardsApy)
      .find('[data-testid="pool-rewards-apy-tooltip-trigger"]')
      .should('not.exist')
    getV2PoolCell(empty, PoolColumnId.GaugeApy)
      .find('[data-testid="pool-gauge-apy-tooltip-trigger"]')
      .should('not.exist')

    const volatile = V2_POOL_FIXTURES.volatile.address
    getV2PoolCell(volatile, PoolColumnId.NetApy).should('contain.text', '5,000+%')
    getV2PoolCell(volatile, PoolColumnId.BaseApy).should('contain.text', '5,000+%')
    getV2PoolCell(volatile, PoolColumnId.WeeklyBaseApy)
      .invoke('text')
      .should('match', /^-\d+\.\d+%$/)
    getV2PoolCell(volatile, PoolColumnId.NetApy)
      .find('[data-testid="pool-net-apy-tooltip-trigger"]')
      .trigger('mouseover')
    cy.get(TOOLTIP).should('contain.text', 'This net APY is volatile and is unlikely to persist.')
    getV2PoolCell(volatile, PoolColumnId.NetApy)
      .find('[data-testid="pool-net-apy-tooltip-trigger"]')
      .trigger('mouseout')
    cy.get(TOOLTIP).should('not.exist')

    const highRewards = V2_POOL_FIXTURES.highRewards.address
    getV2PoolCell(highRewards, PoolColumnId.NetApy).should('not.contain.text', '5,000+%')
    getV2PoolCell(highRewards, PoolColumnId.BaseApy).should('contain.text', '1.005%')
  })
})
