export enum LlamaMarketColumnId {
  Assets = 'assets',
  UserHealth = 'userHealth',
  UserBorrowed = 'userBorrowed',
  UserEarnings = 'userEarnings',
  UserDeposited = 'userDeposited',
  UserHasPosition = 'userHasPosition',
  BorrowRate = 'rates_borrow',
  BorrowChart = 'borrowChart',
  LendRate = 'rates_lend',
  LendChart = 'lendChart',
  UtilizationPercent = 'utilizationPercent',
  LiquidityUsd = 'liquidityUsd',
  Chain = 'chain',
  CollateralSymbol = 'assets_collateral_symbol',
  BorrowedSymbol = 'assets_borrowed_symbol',
  IsFavorite = 'isFavorite',
  Rewards = 'rewards',
  Type = 'type',
}
