export enum LlamaMarketColumnId {
  Assets = 'assets',
  UserHealth = 'userHealth',
  UserBorrowed = 'userBorrowed',
  UserEarnings = 'userEarnings',
  UserDeposited = 'userDeposited',
  UserHasPosition = 'userHasPosition',
  BorrowRate = 'rates.borrow',
  BorrowChart = 'borrowChart',
  LendRate = 'rates.lend',
  LendChart = 'lendChart',
  UtilizationPercent = 'utilizationPercent',
  LiquidityUsd = 'liquidityUsd',
  Chain = 'chain',
  CollateralSymbol = 'assets.collateral.symbol',
  BorrowedSymbol = 'assets.borrowed.symbol',
  IsFavorite = 'isFavorite',
  Rewards = 'rewards',
  Type = 'type',
}
