/**
 * Figma design tokens extracted from the Figma design system.
 * This file is generated by /packages/curve-ui-kit/scripts/figma-tokens
 * DO NOT MODIFY THIS FILE MANUALLY.
 */
export const FIGMA_TOKENS = {
  typography: {
    headingXxl: {
      description: 'to be used only for most important content.',
      fontSize: '64px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-2.56px',
      lineHeight: '64px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    headingMRegular: {
      description: 'to be used only for most important content.',
      fontSize: '32px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-1.28px',
      lineHeight: '36px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    headingMLight: {
      fontSize: '32px',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-1.28px',
      lineHeight: '36px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    headingSLight: {
      description: 'to be used only for most important content.',
      fontSize: '24px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-0.48px',
      lineHeight: '28px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    headingXs: {
      fontSize: '14px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    headingXsLightLc: {
      fontSize: '14px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'capitalize',
    },
    bodyMRegular: {
      description: 'For little labels that organise the interface',
      fontSize: '16px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '24px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    bodyMBold: {
      description: 'For little labels that organise the interface',
      fontSize: '16px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '24px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    bodySRegular: {
      description: 'For little labels that organise the interface',
      fontSize: '14px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    bodySBold: {
      description: 'For little labels that organise the interface',
      fontSize: '14px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    bodyXsRegular: {
      description: 'For little labels that organise the interface',
      fontSize: '12px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    bodyXsBold: {
      description: 'For little labels that organise the interface',
      fontSize: '12px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    buttonLabelXs: {
      fontSize: '14px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    buttonLabelS: {
      fontSize: '14px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '24px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    buttonLabelM: {
      fontSize: '16px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '40px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'uppercase',
    },
    tableHeaderM: {
      fontSize: '16px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableHeaderS: {
      fontSize: '14px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableCellL: {
      fontSize: '20px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '20px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableCellsMRegular: {
      fontSize: '16px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableCellsMBold: {
      fontSize: '16px',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableCellsSRegular: {
      fontSize: '14px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    tableCellsSBold: {
      fontSize: '14px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueXsNotional: {
      fontSize: '12px',
      fontWeight: 500,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueXs: {
      fontSize: '12px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '14px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueS: {
      fontSize: '14px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueM: {
      fontSize: '16px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '16px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueL: {
      fontSize: '24px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '0px',
      lineHeight: '24px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueXl: {
      fontSize: '32px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-1.28px',
      lineHeight: '36px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
    valueXxl: {
      fontSize: '64px',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: '-2.56px',
      lineHeight: '64px',
      textDecoration: 'none',
      fontFamily: 'Mona Sans',
      textIndent: 0,
      textTransform: 'none',
    },
  },
  primitives: {
    grays: {
      '10': '#fdfcfcff',
      '25': '#fafafaff',
      '50': '#f8f7f7ff',
      '75': '#f6f4f4ff',
      '100': '#eeecebff',
      '150': '#e7e4e2ff',
      '200': '#dedbd8ff',
      '300': '#d4d0ccff',
      '400': '#bbb6afff',
      '500': '#968e84ff',
      '600': '#746e66ff',
      '700': '#5a554fff',
      '750': '#494540ff',
      '800': '#3b3834ff',
      '850': '#302e2aff',
      '900': '#252420ff',
      '950': '#1f1e1bff',
      '975': '#191815ff',
    },
    greens: {
      '100': '#d4f7e3ff',
      '200': '#a8efc6ff',
      '300': '#32ce79ff',
      '400': '#27b86cff',
      '500': '#1fa25eff',
      '600': '#167d4aff',
      '700': '#0f5c38ff',
      '800': '#0b3d26ff',
    },
    reds: {
      '200': '#ffd88bff',
      '300': '#ffc300ff',
      '400': '#f77f00ff',
      '500': '#ed242fff',
      '600': '#d41e26ff',
      '700': '#b0151fff',
      '800': '#8c111cff',
    },
    blues: {
      '50': '#fefaefff',
      '100': '#d5dbf0ff',
      '200': '#acbef1ff',
      '300': '#839ff2ff',
      '400': '#5a81f3ff',
      '500': '#3162f4ff',
      '600': '#2c55d5ff',
      '700': '#2747b5ff',
      '800': '#223995ff',
      '900': '#1d2c75ff',
      '950': '#171e55ff',
    },
    violet: {
      '50': '#efedfcff',
      '100': '#dbd9f7ff',
      '200': '#c6c4f2ff',
      '300': '#b0aeeeff',
      '400': '#9997e2ff',
      '500': '#6a68b7ff',
      '600': '#5f5caeff',
      '700': '#554fa5ff',
      '800': '#4a4395ff',
      '900': '#3e3684ff',
      '950': '#2f2862ff',
    },
    spacing: {
      '50': 0,
      '100': 2,
      '200': 4,
      '300': 8,
      '350': 14,
      '400': 16,
      '500': 24,
      '600': 32,
      '700': 48,
      '800': 64,
    },
    sizing: {
      '50': 4,
      '100': 8,
      '125': 12,
      '150': 14,
      '200': 16,
      '250': 20,
      '300': 24,
      '350': 28,
      '400': 32,
      '500': 40,
      '600': 48,
      '700': 64,
      '800': 88,
    },
  },
  effects: {
    activetabshadow: {
      '0': {
        shadowType: 'dropShadow',
        radius: 0,
        color: '#0e3f7e0a',
        offsetX: 0,
        offsetY: 0,
        spread: 1,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 1,
        color: '#2a33450a',
        offsetX: 1,
        offsetY: 0,
        spread: -0.5,
      },
      '2': {
        shadowType: 'dropShadow',
        radius: 3,
        color: '#2a33460a',
        offsetX: 3,
        offsetY: 0,
        spread: -1.5,
      },
      '3': {
        shadowType: 'dropShadow',
        radius: 6,
        color: '#2a33460a',
        offsetX: 6,
        offsetY: 0,
        spread: -3,
      },
      '4': {
        shadowType: 'dropShadow',
        radius: 1,
        color: '#2a33450a',
        offsetX: -1,
        offsetY: 0,
        spread: -0.5,
      },
      '5': {
        shadowType: 'dropShadow',
        radius: 3,
        color: '#2a33460a',
        offsetX: -3,
        offsetY: 0,
        spread: -1.5,
      },
      '6': {
        shadowType: 'dropShadow',
        radius: 6,
        color: '#2a33460a',
        offsetX: -6,
        offsetY: 0,
        spread: -3,
      },
      description: null,
    },
    elevation: {
      'level 3': {
        '0': {
          shadowType: 'dropShadow',
          radius: 0,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 0,
          spread: 1,
        },
        '1': {
          shadowType: 'dropShadow',
          radius: 1,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 1,
          spread: -0.5,
        },
        '2': {
          shadowType: 'dropShadow',
          radius: 3,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 3,
          spread: -1.5,
        },
        '3': {
          shadowType: 'dropShadow',
          radius: 8,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 8,
          spread: -4,
        },
        '4': {
          shadowType: 'dropShadow',
          radius: 16,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 16,
          spread: -8,
        },
        '5': {
          shadowType: 'dropShadow',
          radius: 32,
          color: '#2a33451a',
          offsetX: 0,
          offsetY: 32,
          spread: -16,
        },
        description: null,
      },
      'level 2': {
        '0': {
          shadowType: 'dropShadow',
          radius: 0,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 0,
          spread: 1,
        },
        '1': {
          shadowType: 'dropShadow',
          radius: 1,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 1,
          spread: -0.5,
        },
        '2': {
          shadowType: 'dropShadow',
          radius: 3,
          color: '#2a334624',
          offsetX: 0,
          offsetY: 3,
          spread: -1.5,
        },
        '3': {
          shadowType: 'dropShadow',
          radius: 6,
          color: '#2a334624',
          offsetX: 0,
          offsetY: 6,
          spread: -3,
        },
        '4': {
          shadowType: 'dropShadow',
          radius: 8,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 8,
          spread: -6,
        },
        '5': {
          shadowType: 'dropShadow',
          radius: 12,
          color: '#2a334514',
          offsetX: 0,
          offsetY: 12,
          spread: -6,
        },
        description: null,
      },
      'level 1': {
        '0': {
          shadowType: 'dropShadow',
          radius: 0,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 0,
          spread: 1,
        },
        '1': {
          shadowType: 'dropShadow',
          radius: 1,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 1,
          spread: -0.5,
        },
        '2': {
          shadowType: 'dropShadow',
          radius: 3,
          color: '#2a334624',
          offsetX: 0,
          offsetY: 3,
          spread: -1.5,
        },
        '3': {
          shadowType: 'dropShadow',
          radius: 4,
          color: '#2a334524',
          offsetX: 0,
          offsetY: 4,
          spread: -2,
        },
        '4': {
          shadowType: 'dropShadow',
          radius: 8,
          color: '#2a334514',
          offsetX: 0,
          offsetY: 8,
          spread: -8,
        },
        description: null,
      },
      'level -1': {
        shadowType: 'innerShadow',
        radius: 0,
        color: '#3b3833ff',
        offsetX: 1,
        offsetY: 1,
        spread: 0,
      },
      'level -2': {
        shadowType: 'innerShadow',
        radius: 0,
        color: '#3b3833ff',
        offsetX: 2,
        offsetY: 2,
        spread: 0,
      },
    },
  },
  grid: {
    '12-col_main': {
      pattern: 'columns',
      gutterSize: 24,
      alignment: 'stretch',
      count: 12,
      offset: 36,
    },
    '12-col_cards': {
      pattern: 'columns',
      gutterSize: 24,
      alignment: 'stretch',
      count: 12,
      offset: 24,
    },
    'no margin': {
      '12-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 12,
        offset: 0,
      },
      '11-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 11,
        offset: 0,
      },
      '10-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 10,
        offset: 0,
      },
      '9-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 9,
        offset: 0,
      },
      '8-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 8,
        offset: 0,
      },
      '7-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 7,
        offset: 0,
      },
      '6-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 6,
        offset: 0,
      },
      '5-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 5,
        offset: 0,
      },
      '4-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 4,
        offset: 0,
      },
      '3-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 3,
        offset: 0,
      },
      '2-col': {
        pattern: 'columns',
        gutterSize: 24,
        alignment: 'stretch',
        count: 2,
        offset: 0,
      },
    },
  },
  surfacesAndText: {
    default: {
      light: {
        text: {
          primary: '#1f1e1bff',
          secondary: '#5a554fff',
          tertiary: '#968e84ff',
          highlight: '#3162f4ff',
          disabled: '#bbb6afff',
        },
        layer: {
          '1': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          '2': {
            fill: '#eeecebff',
            outline: '#dedbd8ff',
          },
          '3': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          highlight: '#3162f4ff',
        },
        tables: {
          'header fill': '#dedbd8ff',
        },
      },
      dark: {
        text: {
          primary: '#f8f7f7ff',
          secondary: '#d4d0ccff',
          tertiary: '#bbb6afff',
          highlight: '#3162f4ff',
          disabled: '#968e84ff',
        },
        layer: {
          '1': {
            fill: '#1f1e1bff',
            outline: '#252420ff',
          },
          '2': {
            fill: '#252420ff',
            outline: '#3b3834ff',
          },
          '3': {
            fill: '#3b3834ff',
            outline: '#5a554fff',
          },
          highlight: '#3162f4ff',
        },
        tables: {
          'header fill': '#3b3834ff',
        },
      },
      chad: {
        text: {
          primary: '#1f1e1bff',
          secondary: '#5a554fff',
          tertiary: '#968e84ff',
          highlight: '#5f5caeff',
          disabled: '#bbb6afff',
        },
        layer: {
          '1': {
            fill: '#dbd9f7ff',
            outline: '#b0aeeeff',
          },
          '2': {
            fill: '#c6c4f2ff',
            outline: '#9997e2ff',
          },
          '3': {
            fill: '#b0aeeeff',
            outline: '#6a68b7ff',
          },
          highlight: '#4a4395ff',
        },
        tables: {
          'header fill': '#9997e2ff',
        },
      },
    },
    inverted: {
      light: {
        text: {
          primary: '#f8f7f7ff',
          secondary: '#d4d0ccff',
          tertiary: '#bbb6afff',
          highlight: '#3162f4ff',
          disabled: '#968e84ff',
        },
        layer: {
          '1': {
            fill: '#1f1e1bff',
            outline: '#746e66ff',
          },
          '2': {
            fill: '#252420ff',
            outline: '#494540ff',
          },
          '3': {
            fill: '#494540ff',
            outline: '#746e66ff',
          },
          highlight: '#3162f4ff',
        },
        tables: {
          'header fill': '#3b3834ff',
        },
      },
      dark: {
        text: {
          primary: '#1f1e1bff',
          secondary: '#5a554fff',
          tertiary: '#746e66ff',
          highlight: '#3162f4ff',
          disabled: '#bbb6afff',
        },
        layer: {
          '1': {
            fill: '#f6f4f4ff',
            outline: '#d4d0ccff',
          },
          '2': {
            fill: '#eeecebff',
            outline: '#dedbd8ff',
          },
          '3': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          highlight: '#3162f4ff',
        },
        tables: {
          'header fill': '#dedbd8ff',
        },
      },
      chad: {
        text: {
          primary: '#f8f7f7ff',
          secondary: '#d4d0ccff',
          tertiary: '#bbb6afff',
          highlight: '#9997e2ff',
          disabled: '#968e84ff',
        },
        layer: {
          '1': {
            fill: '#2f2862ff',
            outline: '#4a4395ff',
          },
          '2': {
            fill: '#4a4395ff',
            outline: '#5f5caeff',
          },
          '3': {
            fill: '#554fa5ff',
            outline: '#6a68b7ff',
          },
          highlight: '#9997e2ff',
        },
        tables: {
          'header fill': '#4a4395ff',
        },
      },
    },
  },
  mappedSizesAndSpaces: {
    desktop: {
      radius: {
        round: 9999,
        xs: 4,
        sm: 8,
        md: 24,
        lg: 48,
        xl: 64,
      },
      typography: {
        lineheight: {
          xs: 14,
          sm: 16,
          md: 24,
          lg: 28,
          xl: 40,
          xxl: 64,
        },
        fontweight: {
          'extra light': 200,
          light: 300,
          normal: 400,
          medium: 500,
          'semi bold': 600,
          bold: 700,
          'extra bold': 800,
        },
        fontsize: {
          xs: 12,
          sm: 14,
          md: 16,
          lg: 24,
          xl: 32,
          xxl: 64,
        },
      },
      spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
        xxs: 2,
      },
      sizing: {
        xxs: 8,
        xs: 16,
        sm: 24,
        md: 32,
        lg: 40,
        xl: 48,
        xxl: 64,
        '3xl': 88,
      },
      iconsize: {
        xxs: 12,
        xs: 14,
        sm: 16,
        md: 20,
        lg: 28,
        xl: 40,
        xxl: 48,
        '3xl': 64,
        '4xl': 88,
      },
      grid: {
        'column spacing': 24,
        'row spacing': 24,
      },
    },
    mobile: {
      radius: {
        round: 9999,
        xs: 2,
        sm: 4,
        md: 16,
        lg: 32,
        xl: 48,
      },
      typography: {
        lineheight: {
          xs: 12,
          sm: 14,
          md: 16,
          lg: 24,
          xl: 32,
          xxl: 40,
        },
        fontweight: {
          'extra light': 200,
          light: 300,
          normal: 400,
          medium: 500,
          'semi bold': 600,
          bold: 700,
          'extra bold': 800,
        },
        fontsize: {
          xs: 12,
          sm: 14,
          md: 16,
          lg: 20,
          xl: 28,
          xxl: 40,
        },
      },
      spacing: {
        xs: 2,
        sm: 4,
        md: 8,
        lg: 16,
        xl: 24,
        xxl: 32,
        xxs: 2,
      },
      sizing: {
        xxs: 4,
        xs: 14,
        sm: 16,
        md: 24,
        lg: 32,
        xl: 40,
        xxl: 48,
        '3xl': 64,
      },
      iconsize: {
        xxs: 8,
        xs: 12,
        sm: 14,
        md: 20,
        lg: 24,
        xl: 32,
        xxl: 40,
        '3xl': 48,
        '4xl': 64,
      },
      grid: {
        'column spacing': 24,
        'row spacing': 24,
      },
    },
  },
  themes: {
    desktop: {
      light: {
        layer: {
          '1': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          '2': {
            fill: '#eeecebff',
            outline: '#dedbd8ff',
          },
          '3': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          highlight: {
            outline: '#3162f4ff',
            fill: '#3162f4ff',
          },
          app: {
            background: '#f0edebff',
          },
        },
        text: {
          textcolors: {
            primary: '#1f1e1bff',
            secondary: '#5a554fff',
            tertiary: '#968e84ff',
            highlight: '#3162f4ff',
            disabled: '#bbb6afff',
            success: '#1fa25eff',
            alert: '#ed242fff',
            warning: '#f77f00ff',
          },
          fontfamily: {
            heading: 'Mona Sans',
            body: 'Mona Sans',
            mono: 'Mona Sans',
            button: 'Mona Sans',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#32ce79ff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#fafafaff',
            '50': '#f8f7f7ff',
            '75': '#f6f4f4ff',
            '100': '#eeecebff',
            '150': '#e7e4e2ff',
            '200': '#dedbd8ff',
            '300': '#d4d0ccff',
            '400': '#bbb6afff',
            '500': '#968e84ff',
            '600': '#746e66ff',
            '700': '#5a554fff',
            '750': '#494540ff',
            '800': '#3b3834ff',
            '850': '#302e2aff',
            '900': '#252420ff',
            '950': '#1f1e1bff',
            '975': '#191815ff',
          },
          primary: {
            '50': '#fefaefff',
            '100': '#d5dbf0ff',
            '200': '#acbef1ff',
            '300': '#839ff2ff',
            '400': '#5a81f3ff',
            '500': '#3162f4ff',
            '600': '#2c55d5ff',
            '700': '#2747b5ff',
            '800': '#223995ff',
            '900': '#1d2c75ff',
            '950': '#171e55ff',
          },
          secondary: {
            '100': '#d4f7e3ff',
            '200': '#a8efc6ff',
            '300': '#32ce79ff',
            '400': '#27b86cff',
            '500': '#1fa25eff',
            '600': '#167d4aff',
            '700': '#0f5c38ff',
            '800': '#0b3d26ff',
          },
          tertiary: {
            '200': '#ffd88bff',
            '300': '#ffc300ff',
            '400': '#f77f00ff',
            '600': '#ed242fff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#3162f4ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#3162f4ff',
          secondary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#252420ff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#3162f4ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#252420ff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#27b86cff',
            },
            hover: {
              'label & icon': '#32ce79ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#968e84ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#f8f7f7ff',
              'label & icon 2': '#1f1e1bff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              outline: '#bbb6afff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#5a554fff',
              fill: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            current: {
              'label & icon': '#3162f4ff',
              fill: '#f8f7f7ff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#dedbd8ff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
            'container border': '#d4d0ccff',
          },
          overlined: {
            default: {
              'label & icon': '#968e84ff',
              outline: '#dedbd8ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#3162f4ff',
              fill: '#f8f7f7ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#1f1e1bff',
          },
          hover: {
            'label & icon': '#3162f4ff',
            fill: '#f8f7f7ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
          },
        },
        radius: {
          md: 24,
          xl: 48,
          sm: 8,
          xs: 4,
          square: 0,
          rounded: 9999,
        },
        chips: {
          default: {
            'label & icon': '#5a554fff',
            fill: '#eeecebff',
            stroke: '#dedbd8ff',
          },
          hover: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
          },
          current: {
            'label & icon': '#3162f4ff',
            fill: '#eeecebff',
            outline: '#3162f4ff',
          },
        },
        table: {
          'header fill': '#dedbd8ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#eeecebff',
              border: {
                default: '#bbb6afff',
                error: '#ed242fff',
                active: '#3162f4ff',
                filled: '#302e2aff',
              },
            },
            nested: {
              nested: '#fdfcfcff',
              fill: '#eeecebff',
              border: {
                default: '#bbb6afff',
                active: '#3162f4ff',
                filled: '#302e2aff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#e7e4e2ff',
            },
          },
        },
      },
      dark: {
        layer: {
          '1': {
            fill: '#1f1e1bff',
            outline: '#252420ff',
          },
          '2': {
            fill: '#252420ff',
            outline: '#3b3834ff',
          },
          '3': {
            fill: '#3b3834ff',
            outline: '#5a554fff',
          },
          highlight: {
            outline: '#3162f4ff',
            fill: '#3162f4ff',
          },
          app: {
            background: '#12110fff',
          },
        },
        text: {
          textcolors: {
            primary: '#f8f7f7ff',
            secondary: '#d4d0ccff',
            tertiary: '#bbb6afff',
            highlight: '#3162f4ff',
            disabled: '#968e84ff',
            success: '#27b86cff',
            alert: '#ed242fff',
            warning: '#ffc300ff',
          },
          fontfamily: {
            heading: 'Mona Sans',
            body: 'Mona Sans',
            mono: 'Mona Sans',
            button: 'Mona Sans',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#27b86cff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#191815ff',
            '50': '#1f1e1bff',
            '75': '#252420ff',
            '100': '#302e2aff',
            '150': '#3b3834ff',
            '200': '#494540ff',
            '300': '#5a554fff',
            '400': '#746e66ff',
            '500': '#968e84ff',
            '600': '#bbb6afff',
            '700': '#d4d0ccff',
            '750': '#dedbd8ff',
            '800': '#e7e4e2ff',
            '850': '#eeecebff',
            '900': '#f6f4f4ff',
            '950': '#f8f7f7ff',
            '975': '#fafafaff',
          },
          primary: {
            '50': '#171e55ff',
            '100': '#1d2c75ff',
            '200': '#223995ff',
            '300': '#2747b5ff',
            '400': '#2c55d5ff',
            '500': '#3162f4ff',
            '600': '#5a81f3ff',
            '700': '#839ff2ff',
            '800': '#acbef1ff',
            '900': '#d5dbf0ff',
            '950': '#fefaefff',
          },
          secondary: {
            '100': '#0b3d26ff',
            '200': '#0f5c38ff',
            '300': '#167d4aff',
            '400': '#1fa25eff',
            '500': '#27b86cff',
            '600': '#32ce79ff',
            '700': '#a8efc6ff',
            '800': '#d4f7e3ff',
          },
          tertiary: {
            '200': '#ed242fff',
            '300': '#f77f00ff',
            '400': '#ffc300ff',
            '600': '#ffd88bff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            hover: {
              'label & icon': '#252420ff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#3162f4ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#3162f4ff',
          secondary: {
            default: {
              'label & icon': '#252420ff',
              fill: '#f8f7f7ff',
            },
            hover: {
              'label & icon': '#252420ff',
              fill: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#1f1e1bff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#f8f7f7ff',
            },
            hover: {
              'label & icon': '#223995ff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#302e2aff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#32ce79ff',
            },
            hover: {
              'label & icon': '#1fa25eff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#bbb6afff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#1f1e1bff',
              'label & icon 2': '#f8f7f7ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#f8f7f7ff',
              outline: '#5a554fff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              outline: '#968e84ff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#d4d0ccff',
              fill: '#494540ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#f6f4f4ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#1f1e1bff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#f8f7f7ff',
              outline: '#3b3834ff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
            'container border': '#252420ff',
          },
          overlined: {
            default: {
              'label & icon': '#bbb6afff',
              outline: '#3b3834ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              outline: '#3162f4ff',
              fill: '#3b3834ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#f8f7f7ff',
          },
          hover: {
            'label & icon': '#3162f4ff',
            fill: '#3b3834ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#f6f4f4ff',
          },
        },
        radius: {
          md: 24,
          xl: 48,
          sm: 8,
          xs: 4,
          square: 0,
          rounded: 9999,
        },
        chips: {
          default: {
            'label & icon': '#d4d0ccff',
            fill: '#252420ff',
            stroke: '#3b3834ff',
          },
          hover: {
            'label & icon': '#1f1e1bff',
            fill: '#f6f4f4ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
            outline: '#3162f4ff',
          },
        },
        table: {
          'header fill': '#3b3834ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#302e2aff',
              border: {
                default: '#746e66ff',
                error: '#ed242fff',
                active: '#3162f4ff',
                filled: '#f6f4f4ff',
              },
            },
            nested: {
              nested: '#302e2aff',
              fill: '#302e2aff',
              border: {
                default: '#746e66ff',
                active: '#3162f4ff',
                filled: '#f6f4f4ff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#191815ff',
            },
          },
        },
      },
      chad: {
        layer: {
          '1': {
            fill: '#dbd9f7ff',
            outline: '#b0aeeeff',
          },
          '2': {
            fill: '#c6c4f2ff',
            outline: '#9997e2ff',
          },
          '3': {
            fill: '#b0aeeeff',
            outline: '#6a68b7ff',
          },
          highlight: {
            outline: '#4a4395ff',
            fill: '#4a4395ff',
          },
          app: {
            background: '#f2f2f7ff',
          },
        },
        text: {
          textcolors: {
            primary: '#1f1e1bff',
            secondary: '#5a554fff',
            tertiary: '#968e84ff',
            highlight: '#5f5caeff',
            disabled: '#bbb6afff',
            success: '#1fa25eff',
            alert: '#ed242fff',
            warning: '#f77f00ff',
          },
          fontfamily: {
            heading: 'Minecraft',
            body: 'Hubot Sans',
            mono: 'Hubot Sans',
            button: 'Minecraft',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#27b86cff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#fafafaff',
            '50': '#f8f7f7ff',
            '75': '#f6f4f4ff',
            '100': '#eeecebff',
            '150': '#e7e4e2ff',
            '200': '#dedbd8ff',
            '300': '#d4d0ccff',
            '400': '#bbb6afff',
            '500': '#968e84ff',
            '600': '#746e66ff',
            '700': '#5a554fff',
            '750': '#494540ff',
            '800': '#3b3834ff',
            '850': '#302e2aff',
            '900': '#252420ff',
            '950': '#1f1e1bff',
            '975': '#191815ff',
          },
          primary: {
            '50': '#efedfcff',
            '100': '#dbd9f7ff',
            '200': '#c6c4f2ff',
            '300': '#b0aeeeff',
            '400': '#9997e2ff',
            '500': '#6a68b7ff',
            '600': '#5f5caeff',
            '700': '#554fa5ff',
            '800': '#4a4395ff',
            '900': '#3e3684ff',
            '950': '#2f2862ff',
          },
          secondary: {
            '100': '#d4f7e3ff',
            '200': '#a8efc6ff',
            '300': '#32ce79ff',
            '400': '#27b86cff',
            '500': '#1fa25eff',
            '600': '#167d4aff',
            '700': '#0f5c38ff',
            '800': '#0b3d26ff',
          },
          tertiary: {
            '200': '#ffd88bff',
            '300': '#ffc300ff',
            '400': '#f77f00ff',
            '600': '#ed242fff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#6a68b7ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#5f5caeff',
          secondary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3e3684ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#2f2862ff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#5f5caeff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#2f2862ff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#27b86cff',
            },
            hover: {
              'label & icon': '#1fa25eff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#968e84ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#dbd9f7ff',
              'label & icon 2': '#1f1e1bff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              fill: '#4a4395ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#6a68b7ff',
              outline: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              outline: '#bbb6afff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#5a554fff',
              fill: '#c6c4f2ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#2f2862ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              fill: '#dbd9f7ff',
              outline: '#4a4395ff',
            },
            active: {
              'label & icon': '#252420ff',
              fill: '#4a4395ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#9997e2ff',
            },
            hover: {
              'label & icon': '#5f5caeff',
              outline: '#4a4395ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#4a4395ff',
            },
            active: {
              'label & icon': '#5f5caeff',
              outline: '#968e84ff',
            },
            'container border': '#b0aeeeff',
          },
          overlined: {
            default: {
              'label & icon': '#968e84ff',
              outline: '#9997e2ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#5f5caeff',
              outline: '#4a4395ff',
              fill: '#b0aeeeff',
            },
            active: {
              'label & icon': '#5f5caeff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#1f1e1bff',
          },
          hover: {
            'label & icon': '#5f5caeff',
            fill: '#b0aeeeff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#4a4395ff',
          },
        },
        radius: {
          md: 0,
          xl: 0,
          sm: 0,
          xs: 0,
          square: 0,
          rounded: 0,
        },
        chips: {
          default: {
            'label & icon': '#5a554fff',
            fill: '#dbd9f7ff',
            stroke: '#9997e2ff',
          },
          hover: {
            'label & icon': '#f8f7f7ff',
            fill: '#2f2862ff',
          },
          current: {
            'label & icon': '#1f1e1bff',
            fill: '#c6c4f2ff',
            outline: '#4a4395ff',
          },
        },
        table: {
          'header fill': '#9997e2ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#efedfcff',
              border: {
                default: '#c6c4f2ff',
                error: '#ed242fff',
                active: '#5f5caeff',
                filled: '#9997e2ff',
              },
            },
            nested: {
              nested: '#efedfcff',
              fill: '#efedfcff',
              border: {
                default: '#c6c4f2ff',
                active: '#5f5caeff',
                filled: '#9997e2ff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#efedfcff',
            },
          },
        },
      },
    },
    mobile: {
      light: {
        layer: {
          '1': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          '2': {
            fill: '#eeecebff',
            outline: '#dedbd8ff',
          },
          '3': {
            fill: '#f8f7f7ff',
            outline: '#d4d0ccff',
          },
          highlight: {
            outline: '#3162f4ff',
            fill: '#3162f4ff',
          },
          app: {
            background: '#f0edebff',
          },
        },
        text: {
          textcolors: {
            primary: '#1f1e1bff',
            secondary: '#5a554fff',
            tertiary: '#968e84ff',
            highlight: '#3162f4ff',
            disabled: '#bbb6afff',
            success: '#1fa25eff',
            alert: '#ed242fff',
            warning: '#f77f00ff',
          },
          fontfamily: {
            heading: 'Mona Sans',
            body: 'Mona Sans',
            mono: 'Mona Sans',
            button: 'Mona Sans',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#32ce79ff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#fafafaff',
            '50': '#f8f7f7ff',
            '75': '#f6f4f4ff',
            '100': '#eeecebff',
            '150': '#e7e4e2ff',
            '200': '#dedbd8ff',
            '300': '#d4d0ccff',
            '400': '#bbb6afff',
            '500': '#968e84ff',
            '600': '#746e66ff',
            '700': '#5a554fff',
            '750': '#494540ff',
            '800': '#3b3834ff',
            '850': '#302e2aff',
            '900': '#252420ff',
            '950': '#1f1e1bff',
            '975': '#191815ff',
          },
          primary: {
            '50': '#fefaefff',
            '100': '#d5dbf0ff',
            '200': '#acbef1ff',
            '300': '#839ff2ff',
            '400': '#5a81f3ff',
            '500': '#3162f4ff',
            '600': '#2c55d5ff',
            '700': '#2747b5ff',
            '800': '#223995ff',
            '900': '#1d2c75ff',
            '950': '#171e55ff',
          },
          secondary: {
            '100': '#d4f7e3ff',
            '200': '#a8efc6ff',
            '300': '#32ce79ff',
            '400': '#27b86cff',
            '500': '#1fa25eff',
            '600': '#167d4aff',
            '700': '#0f5c38ff',
            '800': '#0b3d26ff',
          },
          tertiary: {
            '200': '#ffd88bff',
            '300': '#ffc300ff',
            '400': '#f77f00ff',
            '600': '#ed242fff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#3162f4ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#3162f4ff',
          secondary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#252420ff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#3162f4ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#252420ff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#27b86cff',
            },
            hover: {
              'label & icon': '#32ce79ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#968e84ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#f8f7f7ff',
              'label & icon 2': '#1f1e1bff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              outline: '#bbb6afff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#5a554fff',
              fill: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            current: {
              'label & icon': '#3162f4ff',
              fill: '#f8f7f7ff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#dedbd8ff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
            'container border': '#d4d0ccff',
          },
          overlined: {
            default: {
              'label & icon': '#968e84ff',
              outline: '#dedbd8ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#3162f4ff',
              fill: '#f8f7f7ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#1f1e1bff',
          },
          hover: {
            'label & icon': '#3162f4ff',
            fill: '#f8f7f7ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
          },
        },
        radius: {
          md: 16,
          xl: 32,
          sm: 4,
          xs: 2,
          square: 0,
          rounded: 9999,
        },
        chips: {
          default: {
            'label & icon': '#5a554fff',
            fill: '#eeecebff',
            stroke: '#dedbd8ff',
          },
          hover: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
          },
          current: {
            'label & icon': '#3162f4ff',
            fill: '#eeecebff',
            outline: '#3162f4ff',
          },
        },
        table: {
          'header fill': '#dedbd8ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#eeecebff',
              border: {
                default: '#bbb6afff',
                error: '#ed242fff',
                active: '#3162f4ff',
                filled: '#302e2aff',
              },
            },
            nested: {
              nested: '#fdfcfcff',
              fill: '#eeecebff',
              border: {
                default: '#bbb6afff',
                active: '#3162f4ff',
                filled: '#302e2aff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#e7e4e2ff',
            },
          },
        },
      },
      dark: {
        layer: {
          '1': {
            fill: '#1f1e1bff',
            outline: '#252420ff',
          },
          '2': {
            fill: '#252420ff',
            outline: '#3b3834ff',
          },
          '3': {
            fill: '#3b3834ff',
            outline: '#5a554fff',
          },
          highlight: {
            outline: '#3162f4ff',
            fill: '#3162f4ff',
          },
          app: {
            background: '#12110fff',
          },
        },
        text: {
          textcolors: {
            primary: '#f8f7f7ff',
            secondary: '#d4d0ccff',
            tertiary: '#bbb6afff',
            highlight: '#3162f4ff',
            disabled: '#968e84ff',
            success: '#27b86cff',
            alert: '#ed242fff',
            warning: '#ffc300ff',
          },
          fontfamily: {
            heading: 'Mona Sans',
            body: 'Mona Sans',
            mono: 'Mona Sans',
            button: 'Mona Sans',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#27b86cff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#191815ff',
            '50': '#1f1e1bff',
            '75': '#252420ff',
            '100': '#302e2aff',
            '150': '#3b3834ff',
            '200': '#494540ff',
            '300': '#5a554fff',
            '400': '#746e66ff',
            '500': '#968e84ff',
            '600': '#bbb6afff',
            '700': '#d4d0ccff',
            '750': '#dedbd8ff',
            '800': '#e7e4e2ff',
            '850': '#eeecebff',
            '900': '#f6f4f4ff',
            '950': '#f8f7f7ff',
            '975': '#fafafaff',
          },
          primary: {
            '50': '#171e55ff',
            '100': '#1d2c75ff',
            '200': '#223995ff',
            '300': '#2747b5ff',
            '400': '#2c55d5ff',
            '500': '#3162f4ff',
            '600': '#5a81f3ff',
            '700': '#839ff2ff',
            '800': '#acbef1ff',
            '900': '#d5dbf0ff',
            '950': '#fefaefff',
          },
          secondary: {
            '100': '#0b3d26ff',
            '200': '#0f5c38ff',
            '300': '#167d4aff',
            '400': '#1fa25eff',
            '500': '#27b86cff',
            '600': '#32ce79ff',
            '700': '#a8efc6ff',
            '800': '#d4f7e3ff',
          },
          tertiary: {
            '200': '#ed242fff',
            '300': '#f77f00ff',
            '400': '#ffc300ff',
            '600': '#ffd88bff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
            hover: {
              'label & icon': '#252420ff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#3162f4ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#3162f4ff',
          secondary: {
            default: {
              'label & icon': '#252420ff',
              fill: '#f8f7f7ff',
            },
            hover: {
              'label & icon': '#252420ff',
              fill: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#1f1e1bff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#f8f7f7ff',
            },
            hover: {
              'label & icon': '#223995ff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              fill: '#302e2aff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#32ce79ff',
            },
            hover: {
              'label & icon': '#1fa25eff',
              fill: '#f8f7f7ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#bbb6afff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#1f1e1bff',
              'label & icon 2': '#f8f7f7ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#f8f7f7ff',
              outline: '#5a554fff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            disabled: {
              'label & icon': '#968e84ff',
              outline: '#968e84ff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#d4d0ccff',
              fill: '#494540ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#f6f4f4ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              fill: '#1f1e1bff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#f8f7f7ff',
              fill: '#3162f4ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#f8f7f7ff',
              outline: '#3b3834ff',
            },
            hover: {
              'label & icon': '#3162f4ff',
              outline: '#3162f4ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              outline: '#3162f4ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
            'container border': '#252420ff',
          },
          overlined: {
            default: {
              'label & icon': '#bbb6afff',
              outline: '#3b3834ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#f8f7f7ff',
              outline: '#3162f4ff',
              fill: '#3b3834ff',
            },
            active: {
              'label & icon': '#3162f4ff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#f8f7f7ff',
          },
          hover: {
            'label & icon': '#3162f4ff',
            fill: '#3b3834ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#f6f4f4ff',
          },
        },
        radius: {
          md: 16,
          xl: 32,
          sm: 4,
          xs: 2,
          square: 0,
          rounded: 9999,
        },
        chips: {
          default: {
            'label & icon': '#d4d0ccff',
            fill: '#252420ff',
            stroke: '#3b3834ff',
          },
          hover: {
            'label & icon': '#1f1e1bff',
            fill: '#f6f4f4ff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#252420ff',
            outline: '#3162f4ff',
          },
        },
        table: {
          'header fill': '#3b3834ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#302e2aff',
              border: {
                default: '#746e66ff',
                error: '#ed242fff',
                active: '#3162f4ff',
                filled: '#f6f4f4ff',
              },
            },
            nested: {
              nested: '#302e2aff',
              fill: '#302e2aff',
              border: {
                default: '#746e66ff',
                active: '#3162f4ff',
                filled: '#f6f4f4ff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#191815ff',
            },
          },
        },
      },
      chad: {
        layer: {
          '1': {
            fill: '#dbd9f7ff',
            outline: '#b0aeeeff',
          },
          '2': {
            fill: '#c6c4f2ff',
            outline: '#9997e2ff',
          },
          '3': {
            fill: '#b0aeeeff',
            outline: '#6a68b7ff',
          },
          highlight: {
            outline: '#4a4395ff',
            fill: '#4a4395ff',
          },
          app: {
            background: '#f2f2f7ff',
          },
        },
        text: {
          textcolors: {
            primary: '#1f1e1bff',
            secondary: '#5a554fff',
            tertiary: '#968e84ff',
            highlight: '#5f5caeff',
            disabled: '#bbb6afff',
            success: '#1fa25eff',
            alert: '#ed242fff',
            warning: '#f77f00ff',
          },
          fontfamily: {
            heading: 'Minecraft',
            body: 'Hubot Sans',
            mono: 'Hubot Sans',
            button: 'Minecraft',
          },
        },
        feedback: {
          warning: '#ffc300ff',
          success: '#27b86cff',
          alert: '#ed242fff',
        },
        color: {
          neutral: {
            '25': '#fafafaff',
            '50': '#f8f7f7ff',
            '75': '#f6f4f4ff',
            '100': '#eeecebff',
            '150': '#e7e4e2ff',
            '200': '#dedbd8ff',
            '300': '#d4d0ccff',
            '400': '#bbb6afff',
            '500': '#968e84ff',
            '600': '#746e66ff',
            '700': '#5a554fff',
            '750': '#494540ff',
            '800': '#3b3834ff',
            '850': '#302e2aff',
            '900': '#252420ff',
            '950': '#1f1e1bff',
            '975': '#191815ff',
          },
          primary: {
            '50': '#efedfcff',
            '100': '#dbd9f7ff',
            '200': '#c6c4f2ff',
            '300': '#b0aeeeff',
            '400': '#9997e2ff',
            '500': '#6a68b7ff',
            '600': '#5f5caeff',
            '700': '#554fa5ff',
            '800': '#4a4395ff',
            '900': '#3e3684ff',
            '950': '#2f2862ff',
          },
          secondary: {
            '100': '#d4f7e3ff',
            '200': '#a8efc6ff',
            '300': '#32ce79ff',
            '400': '#27b86cff',
            '500': '#1fa25eff',
            '600': '#167d4aff',
            '700': '#0f5c38ff',
            '800': '#0b3d26ff',
          },
          tertiary: {
            '200': '#ffd88bff',
            '300': '#ffc300ff',
            '400': '#f77f00ff',
            '600': '#ed242fff',
          },
        },
        button: {
          primary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#6a68b7ff',
            },
          },
          'focus outline width': 2,
          'focus outline': '#5f5caeff',
          secondary: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#3e3684ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#2f2862ff',
            },
          },
          ghost: {
            default: {
              'label & icon': '#5f5caeff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              fill: '#2f2862ff',
            },
          },
          radius: {
            md: 0,
            xs: 0,
            sm: 0,
            lg: 0,
          },
          success: {
            default: {
              'label & icon': '#252420ff',
              fill: '#27b86cff',
            },
            hover: {
              'label & icon': '#1fa25eff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#1f1e1bff',
              fill: '#a8efc6ff',
            },
          },
          alert: {
            default: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
            hover: {
              'label & icon': '#f77f00ff',
              fill: '#252420ff',
            },
            disabled: {
              'label & icon': '#f8f7f7ff',
              fill: '#ed242fff',
            },
          },
          navigation: {
            default: {
              'label & icon': '#968e84ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              fill: '#dbd9f7ff',
              'label & icon 2': '#1f1e1bff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              fill: '#4a4395ff',
            },
          },
          outlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#d4d0ccff',
            },
            hover: {
              'label & icon': '#6a68b7ff',
              outline: '#6a68b7ff',
            },
            disabled: {
              'label & icon': '#bbb6afff',
              outline: '#bbb6afff',
            },
          },
        },
        tabs: {
          contained: {
            default: {
              'label & icon': '#5a554fff',
              fill: '#c6c4f2ff',
            },
            hover: {
              'label & icon': '#f8f7f7ff',
              fill: '#2f2862ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              fill: '#dbd9f7ff',
              outline: '#4a4395ff',
            },
            active: {
              'label & icon': '#252420ff',
              fill: '#4a4395ff',
              outline: '#968e84ff',
            },
          },
          underlined: {
            default: {
              'label & icon': '#1f1e1bff',
              outline: '#9997e2ff',
            },
            hover: {
              'label & icon': '#5f5caeff',
              outline: '#4a4395ff',
            },
            current: {
              'label & icon': '#1f1e1bff',
              outline: '#4a4395ff',
            },
            active: {
              'label & icon': '#5f5caeff',
              outline: '#968e84ff',
            },
            'container border': '#b0aeeeff',
          },
          overlined: {
            default: {
              'label & icon': '#968e84ff',
              outline: '#9997e2ff',
            },
            hover: {
              'label & icon': '#1f1e1bff',
              outline: '#968e84ff',
            },
            current: {
              'label & icon': '#5f5caeff',
              outline: '#4a4395ff',
              fill: '#b0aeeeff',
            },
            active: {
              'label & icon': '#5f5caeff',
              outline: '#968e84ff',
            },
          },
        },
        toggles: {
          default: {
            'label & icon': '#1f1e1bff',
          },
          hover: {
            'label & icon': '#5f5caeff',
            fill: '#b0aeeeff',
          },
          current: {
            'label & icon': '#f8f7f7ff',
            fill: '#4a4395ff',
          },
        },
        radius: {
          md: 0,
          xl: 0,
          sm: 0,
          xs: 0,
          square: 0,
          rounded: 0,
        },
        chips: {
          default: {
            'label & icon': '#5a554fff',
            fill: '#dbd9f7ff',
            stroke: '#9997e2ff',
          },
          hover: {
            'label & icon': '#f8f7f7ff',
            fill: '#2f2862ff',
          },
          current: {
            'label & icon': '#1f1e1bff',
            fill: '#c6c4f2ff',
            outline: '#4a4395ff',
          },
        },
        table: {
          'header fill': '#9997e2ff',
        },
        'input & select': {
          base: {
            default: {
              fill: '#efedfcff',
              border: {
                default: '#c6c4f2ff',
                error: '#ed242fff',
                active: '#5f5caeff',
                filled: '#9997e2ff',
              },
            },
            nested: {
              nested: '#efedfcff',
              fill: '#efedfcff',
              border: {
                default: '#c6c4f2ff',
                active: '#5f5caeff',
                filled: '#9997e2ff',
                error: '#ed242fff',
              },
            },
          },
          large: {
            default: {
              fill: '#efedfcff',
            },
          },
        },
      },
    },
  },
} as const
export type FigmaTokens = typeof FIGMA_TOKENS
