export const TWOCOINCRYPTOSWAP = 'Two Coin Cryptoswap (Old)'
export const TWOCOINCRYPTOSWAPNG = 'Two Coin Cryptoswap'
export const THREECOINCRYPTOSWAP = 'Three Coin Cryptoswap'
export const STABLESWAP = 'Stableswap'
export const STABLESWAPOLD = 'Stableswap (Old)'
