import { NET_SUPPLY_RATE_TITLE } from '@/llamalend/constants'
import { t } from '@evm-ui/lib/i18n'
import { CRVUSD_ROUTES, getInternalUrl } from '@evm-ui/shared/routes'
import { Tooltip } from '@evm-ui/shared/ui/Tooltip'
import Link from '@mui/material/Link'
import Typography from '@mui/material/Typography'

const TooltipContent = () => (
  <Typography variant="bodySRegular">
    {t`Mint markets don't accept direct supply. Users can benefit from the revenue generated by crvUSD by depositing crvUSD into the `}

    <Link href={getInternalUrl('crvusd', 'ethereum', CRVUSD_ROUTES.PAGE_CRVUSD_STAKING)} target="_blank">
      Savings Vault
    </Link>

    {t`, which shares revenue from these markets to the DAO and scrvUSD holders. `}
  </Typography>
)

export const SupplyRateMintTooltip = () => (
  <Tooltip clickable title={NET_SUPPLY_RATE_TITLE} body={<TooltipContent />} placement="top" mobileDrawer>
    <Typography variant="tableCellMBold" color="textPrimary" sx={{ width: '100%' }}>
      -
    </Typography>
  </Tooltip>
)
