import Link from '@mui/material/Link'
import Typography from '@mui/material/Typography'
import { t } from '@ui-kit/lib/i18n'
import { CRVUSD_ROUTES, getInternalUrl } from '@ui-kit/shared/routes'
import { Tooltip } from '@ui-kit/shared/ui/Tooltip'

const TooltipContent = () => (
  <Typography variant="bodySRegular">
    {t`Mint markets don't accept direct supply. Users can benefit from the revenue generated by crvUSD by depositing crvUSD into the `}

    <Link href={getInternalUrl('crvusd', 'ethereum', CRVUSD_ROUTES.PAGE_CRVUSD_STAKING)} target="_blank">
      Savings Vault
    </Link>

    {t`, which shares revenue from these markets to the DAO and scrvUSD holders. `}
  </Typography>
)

export const SupplyRateMintTooltip = () => (
  <Tooltip clickable title={t`Supply Yield`} body={<TooltipContent />} placement="top">
    <Typography variant="tableCellMBold" color="textPrimary" width={'100%'}>
      —
    </Typography>
  </Tooltip>
)
