import { figmaTokens } from './resolve'
import { writeFile } from 'fs/promises'
import { exec } from 'child_process'

const GENERATED_FILE_PATH = 'src/themes/model/figma-tokens.generated.ts'

export const run = (command: string) =>
  new Promise<string>((resolve, reject) => {
    const child = exec(command, (error, stdout, stderr) => {
      error ? reject(error) : resolve(stdout || stderr);
    });
    child.stdout?.pipe(process.stdout);
    child.stderr?.pipe(process.stderr);
  });


/**
 * Writes the figma tokens to a typescript file
 */
async function main() {
  const start = Date.now()
  const json = JSON.stringify(figmaTokens, null, 2)
  const code = `
/**
  * Figma design tokens extracted from the Figma design system.
  * This file is generated by /packages/curve-ui-kit/scripts/figma-tokens
  * DO NOT MODIFY THIS FILE MANUALLY.
  */
export const FIGMA_TOKENS = ${json} as const
export type FigmaTokens = typeof FIGMA_TOKENS
`

  await writeFile(GENERATED_FILE_PATH, code)
  await run(`npx prettier --write ${GENERATED_FILE_PATH}`)
  return `Figma tokens written to ${GENERATED_FILE_PATH} in ${Date.now() - start}ms`
}

main().then(console.log).catch(console.error)
