import { figmaTokens } from './resolve'
import { writeFile } from 'fs/promises'
import { exec } from 'child_process'

export const run = (command: string) =>
  new Promise<string>((resolve, reject) => {
    const child = exec(command, (error, stdout, stderr) => {
      error ? reject(error) : resolve(stdout || stderr);
    });
    child.stdout?.pipe(process.stdout);
    child.stderr?.pipe(process.stderr);
  });


/**
 * Writes the figma tokens to a typescript file
 */
async function main() {
  const filePath = 'src/themes/model/figma-tokens.ts'
  const json = JSON.stringify(figmaTokens, null, 2)
  await writeFile(filePath, `
/**
  * Figma design tokens extracted from the Figma design system.
  * This file is generated by the figma-tokens script.
  * DO NOT MODIFY THIS FILE MANUALLY.
  */
export const FIGMA_TOKENS = ${json} as const
export type FigmaTokens = typeof FIGMA_TOKENS
`)
  // run prettier
  await run(`npx prettier --write ${filePath}`)

  return `Figma tokens written to ${filePath}`
}

main().then(console.log).catch(console.error)
