export enum MarketColumnId {
  Assets = 'assets',
  UserHealth = 'userHealth',
  UserLiquidationBuffer = 'userLiquidationBuffer',
  UserLiquidationRange = 'userLiquidationRange',
  UserDistanceToRange = 'userDistanceToRange',
  UserBandCount = 'userBandCount',
  UserCollateralComposition = 'userCollateralComposition',
  UserBorrowed = 'userBorrowed',
  UserBoostMultiplier = 'userBoostMultiplier', // only for supply positions
  UserCollateral = 'userCollateral',
  UserLtv = 'userLtv',
  UserReturnOnEquity = 'userRoe',
  UserLeverage = 'userLeverage',
  UserEarnings = 'userEarnings', // only for lend markets
  UserSupplyShare = 'userSupplyShare', // supply positions only
  SupplyIncentivesApr = 'supplyIncentivesApr', // supply positions only
  UserDeposited = 'userDeposited', // only for lend markets
  BorrowRate = 'rates_borrow',
  NetBorrowRate = 'rates_net_borrow',
  CollateralYield = 'collateralYield',
  BorrowChart = 'borrowChart',
  LendRate = 'rates_lend',
  NetSupplyRate = 'rates_net_supply',
  MaxLtv = 'maxLtv',
  MaxLeverage = 'maxLeverage',
  MaxReturnOnEquity = 'maxRoe', // preserve the persisted column ID
  UtilizationPercent = 'utilizationPercent',
  SolvencyPercent = 'solvencyPercent',
  LiquidityUsd = 'liquidityUsd',
  Chain = 'chain',
  CollateralSymbol = 'assets_collateral_symbol',
  BorrowedSymbol = 'assets_borrowed_symbol',
  IsFavorite = 'isFavorite',
  Rewards = 'rewards',
  Tvl = 'tvl',
  TotalDebt = 'totalDebtUsd',
  TotalCollateralUsd = 'totalCollateralUsd',
  DeprecatedMessage = 'deprecatedMessage',
  Type = 'type',
  Version = 'version',
}
