export type { Wallet, CurveApi, LlamaApi } from './lib/types'
export { createWagmiConfig, type WagmiChainId } from './lib/wagmi/wagmi-config'

export { getLib, requireLib } from './lib/utils'
export { useWallet } from './lib/useWallet'
export { useSwitchChain } from './lib/useSwitchChain'
export { notify } from './lib/notify'
export { useCurve, isLoading, isFailure } from './lib/CurveContext'
export { CurveProvider } from './lib/CurveProvider'
export { ConnectWalletIndicator } from './ui/ConnectWalletIndicator'
export { ConnectWalletPrompt } from './ui/ConnectWalletPrompt'
