import { t } from '@ui-kit/lib/i18n'
import type { Partner } from '@ui-kit/shared/ui/PartnerCard'

export const WEB3_BRIDGES: Partner[] = [
  {
    name: 'CrossCurve',
    description: t`A decentralized and unified infrastructure for cross-chain liquidity and incentives, powered by Curve AMM.`,
    imageId: 'platforms/cross-curve.png',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, celo: true, fantom: true, fraxtal: true, gnosis: true, optimism: true, sonic: true, taiko: true, unichain: true },
    appUrl:
      'https://app.crosscurve.fi/swap?inputChainId=7&inputToken=0x498bf2b1e120fed3ad3d42ea2165e9b73f99c1e5&outputChainId=13&utm_source=Curve+Finance&utm_medium=web&utm_campaign=Curve+Bridge+Page',
    twitterUrl: 'https://x.com/crosscurvefi',
  },
  {
    name: 'deBridge',
    description: t`Messaging and cross-chain interoperability protocol enabling the building of cross-chain dapps.`,
    imageId: 'platforms/debridge.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, ethereum: true, gnosis: true, hyperliquid: true, monad: true, optimism: true, polygon: true, sonic: true },
    appUrl: 'https://debridge.com/',
    twitterUrl: 'https://x.com/deBridge',
  },
  {
    name: 'Jumper',
    description: t`Swap and bridge across +20 networks with no fees and best price guarantees.`,
    imageId: 'platforms/jumper.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, celo: true, corn: true, ethereum: true, etherlink: true, fraxtal: true, gnosis: true, hyperliquid: true, ink: true, monad: true, optimism: true, plasma: true, plume: true, polygon: true, sonic: true, stable: true, unichain: true, xdc: true },
    appUrl: 'https://jumper.exchange/',
    twitterUrl: 'https://x.com/JumperExchange',
  },
  {
    name: 'Across',
    description: t`Fastest and lowest-cost bridging for end-users.`,
    imageId: 'platforms/across.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, celo: true, ethereum: true, fantom: true, fraxtal: true, gnosis: true, monad: true, optimism: true, polygon: true, sonic: true },
    appUrl: 'https://across.to/',
    twitterUrl: 'https://x.com/AcrossProtocol',
  },
  {
    name: 'Synapse',
    description: t`Synapse is the most widely used, extensible, and secure cross-chain communications network.`,
    imageId: 'platforms/synapse.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, ethereum: true, gnosis: true, hyperliquid: true, monad: true, optimism: true, polygon: true, sonic: true },
    appUrl: 'https://synapseprotocol.com/',
    twitterUrl: 'https://x.com/SynapseProtocol',
  },
  {
    name: 'Squid',
    description: t`Squid powers cross-chain swaps and contract calls across chains in a single click.`,
    imageId: 'platforms/squid.jpg',
    networks: { arbitrum: true, avalanche: true, aurora: true, bsc: true, base: true, ethereum: true, fantom: true, optimism: true, polygon: true, unichain: true },
    appUrl: 'https://www.squidrouter.com/',
    twitterUrl: 'https://x.com/squidrouter',
  },
  {
    name: 'Portal',
    description: 'Portal is a multichain app helping you do fast, secure token transfers and swaps between any chain.',
    imageId: 'platforms/portal.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, celo: true, ink: true, monad: true, optimism: true, plume: true, polygon: true, sonic: true, unichain: true },
    appUrl: 'https://portalbridge.com/',
    twitterUrl: 'https://x.com/portalbridge_',
  },
  {
    name: 'Stargate',
    description: 'Stargate is a composable cross-chain liquidity transport protocol enabling seamless asset transfers between blockchains.',
    imageId: 'platforms/stargate.png',
    networks: { arbitrum: true, bsc: true, base: true, corn: true, etherlink: true, fantom: true, fraxtal: true, gnosis: true, hyperliquid: true, ink: true, optimism: true, plasma: true, plume: true, polygon: true, taiko: true, unichain: true, xdc: true },
    appUrl: 'https://stargate.finance/',
    twitterUrl: 'https://x.com/StargateFinance',
  },
  {
    name: 'Superbridge',
    description: 'Bridge ETH and ERC20 tokens into and out of the Superchain.',
    imageId: 'platforms/superbridge.jpg',
    networks: { arbitrum: true, avalanche: true, bsc: true, base: true, celo: true, ink: true, optimism: true, unichain: true },
    appUrl: 'https://superbridge.app/',
    twitterUrl: 'https://x.com/superbridge',
  },
  {
    name: 'brid.gg',
    description: 'Brid.gg is a user-friendly interface, designed to connect Ethereum with next-generation superchains and efficient Layer 2 solutions.',
    imageId: 'platforms/bridgg.png',
    networks: { base: true, fraxtal: true, ink: true, optimism: true, unichain: true },
    appUrl: 'https://www.brid.gg',
  },
  {
    name: 'USDT',
    description: 'USDT0 ensures fast, secure, and cost-efficient cross-chain transfers all while maintaining a strict 1:1 backing with USDT.',
    imageId: 'platforms/usdt0.jpg',
    networks: { arbitrum: true, celo: true, corn: true, ink: true, monad: true, optimism: true, plasma: true, polygon: true, stable: true, unichain: true },
    appUrl: 'https://usdt0.to/transfer',
    twitterUrl: 'https://x.com/USDT0_to',
  },
]

export const NATIVE_BRIDGES: Partner[] = [
  {
    name: 'Arbitrum',
    imageId: 'chains/arbitrum.png',
    appUrl: 'https://arbitrum.io/',
    twitterUrl: 'https://x.com/arbitrum',
  },
  {
    name: 'Aurora',
    imageId: 'chains/aurora.png',
    appUrl: 'https://rainbowbridge.app/',
    twitterUrl: 'https://x.com/auroraisnear',
  },
  {
    name: 'Avalanche',
    imageId: 'chains/avalanche.png',
    appUrl: 'https://core.app/bridge',
    twitterUrl: 'https://x.com/avax',
  },
  {
    name: 'Base',
    imageId: 'chains/base.png',
    appUrl: 'https://superbridge.app/base',
    twitterUrl: 'https://x.com/base',
  },
  {
    name: 'BSC',
    imageId: 'chains/bsc.png',
    appUrl: 'https://www.bnbchain.org/en/bnb-chain-bridge',
    twitterUrl: 'https://x.com/binance',
  },
  {
    name: 'Celo',
    imageId: 'chains/celo.png',
    appUrl: 'https://mondo.celo.org/bridge',
    twitterUrl: 'https://x.com/Celo',
  },
  {
    name: 'Etherlink',
    imageId: 'chains/etherlink.png',
    appUrl: 'https://bridge.etherlink.com/',
    twitterUrl: 'https://x.com/etherlink',
  },
  {
    name: 'Fantom',
    imageId: 'chains/fantom.png',
    appUrl: 'https://portalbridge.com/',
  },
  {
    name: 'Fraxtal',
    imageId: 'chains/fraxtal.png',
    appUrl: 'https://frax.com/swap',
    twitterUrl: 'https://x.com/fraxfinance',
  },
  {
    name: 'Gnosis',
    imageId: 'chains/xdai.png',
    appUrl: 'https://bridge.gnosischain.com/',
    twitterUrl: 'https://x.com/gnosischain',
  },
  {
    name: 'Ink',
    imageId: 'chains/ink.png',
    appUrl: 'https://inkonchain.com/bridge',
    twitterUrl: 'https://x.com/inkonchain',
  },
  {
    name: 'Mantle',
    imageId: 'chains/mantle.png',
    appUrl: 'https://app.mantle.xyz/bridge',
    twitterUrl: 'https://x.com/Mantle_Official',
  },
  {
    name: 'Monad',
    imageId: 'chains/monad.png',
    appUrl: 'https://monadbridge.com/',
    twitterUrl: 'https://x.com/monad_xyz',
  },
  {
    name: 'Optimism',
    imageId: 'chains/optimism.png',
    appUrl: 'https://app.optimism.io/bridge',
    twitterUrl: 'https://x.com/Optimism',
  },
  {
    name: 'Plasma',
    imageId: 'chains/plasma.png',
    appUrl: 'https://stargate.finance/',
    twitterUrl: 'https://x.com/Plasma',
  },
  {
    name: 'Plume',
    imageId: 'chains/plume.png',
    appUrl: 'https://portal.plume.org/bridge',
    twitterUrl: 'https://x.com/plumenetwork',
  },
  {
    name: 'Polygon',
    imageId: 'chains/polygon.png',
    appUrl: 'https://portal.polygon.technology/bridge',
    twitterUrl: 'https://x.com/0xPolygon',
  },
  {
    name: 'Sonic',
    imageId: 'chains/sonic.png',
    appUrl: 'https://my.soniclabs.com/bridge',
    twitterUrl: 'https://x.com/SonicLabs',
  },
  {
    name: 'Stable',
    imageId: 'chains/stable.png',
    appUrl: 'https://stargate.finance/',
    twitterUrl: 'https://x.com/stable',
  },
  {
    name: 'Taiko',
    imageId: 'chains/taiko.png',
    appUrl: 'https://bridge.taiko.xyz/',
    twitterUrl: 'https://x.com/taikoxyz',
  },
  {
    name: 'Unichain',
    imageId: 'chains/unichain.png',
    twitterUrl: 'https://x.com/unichain',
  },
  {
    name: 'XDC Network',
    imageId: 'chains/xdc.png',
    appUrl: 'https://bridge.xdc.org',
    twitterUrl: 'https://x.com/XDCNetwork',
  },
]
