import {
  RCArbitrumLogo,
  RCAvalancheLogo,
  RCAuroraLogo,
  RCCeloLogo,
  RCEthereumLogo,
  RCFantomLogo,
  RCKavaLogo,
  RCMoonbeamLogo,
  RCOptimismLogo,
  RCPolygonLogo,
  RCGnosisLogo,
  RCZksyncLogo,
  RCBaseLogo,
  RCBSCLogo,
  RCFraxtalLogo,
  RCXLayerLogo,
  RCXLayerWhiteLogo,
  RCMantleLogo,
} from 'ui/src/images'

const CURVE_IMAGE_ASSETS_BASE_PATH = 'https://cdn.jsdelivr.net/gh/curvefi/curve-assets'

const NETWORK_CONFIG_DEFAULT = {
  blocknativeSupport: true,
  useApi: true, // default to true when calling fetchPools
  gasL2: false,
  gasPricesUnit: 'GWEI',
  gasPricesUrl: 'https://api.curve.fi/api/getGas',
  gasPricesDefault: 0,
  integrations: {
    imageBaseurl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-assets/platforms',
    listUrl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-external-integrations/integrations-list.json',
    tagsUrl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-external-integrations/integrations-tags.json',
  },
  rewards: {
    baseUrl: 'https://cdn.jsdelivr.net',
    imageBaseUrl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-assets/platforms',
    campaignsUrl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-external-reward@latest/campaign-list.json',
    tagsUrl: 'https://cdn.jsdelivr.net/gh/curvefi/curve-external-reward@latest/reward-tags.json',
  },
  isActiveNetwork: true,
}

export const baseNetworksConfig = {
  1: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Ethereum',
    id: 'ethereum' as const,
    gasPricesDefault: 1,
    hex: '0x1',
    icon: RCEthereumLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets/`,
    networkId: 1 as const,
    orgUIPath: 'https://classic.curve.fi',
    rpcUrlConnectWallet: `https://eth.drpc.org`,
    symbol: 'ETH',
    scanAddressPath: (hash: string) => `https://etherscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://etherscan.com/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://etherscan.io/token/${hash}`,
  },
  10: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Optimism',
    id: 'optimism' as const,
    gasL2: true,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0xa',
    icon: RCOptimismLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-optimism/`,
    networkId: 10 as const,
    orgUIPath: 'https://optimism.curve.fi',
    rpcUrlConnectWallet: 'https://optimism.drpc.org',
    symbol: 'ETH',
    scanAddressPath: (hash: string) => `https://optimistic.etherscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://optimistic.etherscan.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://optimistic.etherscan.io/token/${hash}`,
  },
  100: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Gnosis',
    id: 'xdai' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x64',
    icon: RCGnosisLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-xdai/`,
    networkId: 100 as const,
    orgUIPath: 'https://xdai.curve.fi',
    rpcUrlConnectWallet: 'https://rpc.gnosischain.com',
    symbol: 'XDAI',
    scanAddressPath: (hash: string) => `https://gnosisscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://gnosisscan.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://gnosisscan.io/address/${hash}`,
  },
  1284: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Moonbeam',
    id: 'moonbeam' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x504',
    icon: RCMoonbeamLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-moonbeam/`,
    networkId: 1284 as const,
    orgUIPath: 'https://moonbeam.curve.fi',
    rpcUrlConnectWallet: 'https://moonbeam.public.blastapi.io',
    symbol: 'GLMR',
    scanAddressPath: (hash: string) => `https://moonscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://moonscan.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://moonscan.io/address/${hash}`,
  },
  137: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Polygon',
    id: 'polygon' as const,
    gasPricesUrl: 'https://gasstation.polygon.technology/v2',
    gasPricesDefault: 0,
    hex: '0x89',
    icon: RCPolygonLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-polygon/`,
    networkId: 137 as const,
    orgUIPath: 'https://polygon.curve.fi',
    rpcUrlConnectWallet: 'https://polygon-rpc.com',
    symbol: 'MATIC',
    scanAddressPath: (hash: string) => `https://polygonscan.com/address/${hash}`,
    scanTxPath: (hash: string) => `https://polygonscan.com/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://polygonscan.com/token/${hash}`,
  },
  2222: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Kava',
    id: 'kava' as const,
    gasPricesUnit: 'UKAVA',
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x8ae',
    icon: RCKavaLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-kava/`,
    networkId: 2222 as const,
    orgUIPath: 'https://kava.curve.fi',
    rpcUrlConnectWallet: 'https://evm.kava.io',
    symbol: 'KAVA',
    scanAddressPath: (hash: string) => `https://explorer.kava.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://explorer.kava.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://explorer.kava.io/address/${hash}`,
  },
  250: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Fantom',
    id: 'fantom' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0xfa',
    icon: RCFantomLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-fantom/`,
    networkId: 250 as const,
    orgUIPath: 'https://ftm.curve.fi',
    rpcUrlConnectWallet: 'https://rpc.ftm.tools/',
    symbol: 'FTM',
    scanAddressPath: (hash: string) => `https://ftmscan.com/address/${hash}`,
    scanTxPath: (hash: string) => `https://ftmscan.com/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://ftmscan.com/token/${hash}`,
  },
  42161: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Arbitrum',
    id: 'arbitrum' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0xa4b1',
    icon: RCArbitrumLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-arbitrum/`,
    networkId: 42161 as const,
    orgUIPath: 'https://arbitrum.curve.fi',
    rpcUrlConnectWallet: 'https://arb1.arbitrum.io/rpc',
    symbol: 'ETH',
    scanAddressPath: (hash: string) => `https://arbiscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://arbiscan.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://arbiscan.io/token/${hash}`,
  },
  43114: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Avalanche',
    id: 'avalanche' as const,
    gasPricesUnit: 'nAVAX',
    gasPricesUrl: 'https://api.avax.network/ext/bc/C/rpc',
    gasPricesDefault: 0,
    hex: '0xa86a',
    icon: RCAvalancheLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-avalanche/`,
    networkId: 43114 as const,
    orgUIPath: 'https://avax.curve.fi',
    rpcUrlConnectWallet: 'https://api.avax.network/ext/bc/C/rpc',
    symbol: 'AVAX',
    scanAddressPath: (hash: string) => `https://snowtrace.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://snowtrace.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://snowtrace.io/token/${hash}`,
  },
  42220: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Celo',
    id: 'celo' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0xa4ec',
    icon: RCCeloLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-celo/`,
    networkId: 42220 as const,
    orgUIPath: 'https://celo.curve.fi',
    rpcUrlConnectWallet: 'https://forno.celo.org',
    symbol: 'CELO',
    scanAddressPath: (hash: string) => `https://celoscan.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://celoscan.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://celoscan.io/address/${hash}`,
  },
  1313161554: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Aurora',
    id: 'aurora' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x4e454152',
    icon: RCAuroraLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-aurora/`,
    networkId: 1313161554 as const,
    orgUIPath: 'https://aurora.curve.fi',
    rpcUrlConnectWallet: 'https://mainnet.aurora.dev',
    symbol: 'aETH',
    scanAddressPath: (hash: string) => `https://aurorascan.dev/address/${hash}`,
    scanTxPath: (hash: string) => `https://aurorascan.dev/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://aurorascan.dev/address/${hash}`,
  },
  324: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'zkSync Era',
    id: 'zksync' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x144',
    icon: RCZksyncLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-zksync/`,
    networkId: 324 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: 'https://mainnet.era.zksync.io',
    symbol: 'ETH',
    scanAddressPath: (hash: string) => `https://explorer.zksync.io/address/${hash}`,
    scanTxPath: (hash: string) => `https://explorer.zksync.io/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://explorer.zksync.io/token/${hash}`,
  },
  8453: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Base',
    id: 'base' as const,
    gasL2: true,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0x2105',
    icon: RCBaseLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-base/`,
    networkId: 8453 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: 'https://base.drpc.org',
    symbol: 'ETH',
    scanAddressPath: (hash: string) => `https://basescan.org/address/${hash}`,
    scanTxPath: (hash: string) => `https://basescan.org/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://basescan.org/token/${hash}`,
  },
  56: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'BSC',
    id: 'bsc' as const,
    hex: '0x38',
    icon: RCBSCLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-bsc/`,
    networkId: 56 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: 'https://bsc-dataseed1.binance.org/',
    symbol: 'BNB',
    scanAddressPath: (hash: string) => `https://bscscan.com/address/${hash}`,
    scanTxPath: (hash: string) => `https://bscscan.com/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://bscscan.com/token/${hash}`,
  },
  252: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Fraxtal',
    id: 'fraxtal' as const,
    hex: '0xfc',
    icon: RCFraxtalLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-fraxtal/`,
    networkId: 252 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: `https://rpc.frax.com`,
    symbol: 'frxETH',
    scanAddressPath: (hash: string) => `https://fraxscan.com/address/${hash}`,
    scanTxPath: (hash: string) => `https://fraxscan.com/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://fraxscan.com/token/${hash}`,
  },
  196: {
    ...NETWORK_CONFIG_DEFAULT,
    name: 'X Layer',
    id: 'x-layer' as const,
    gasPricesUrl: '',
    gasPricesDefault: 0,
    hex: '0xc4',
    icon: RCXLayerLogo,
    iconDarkTheme: RCXLayerWhiteLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets-x-layer/`,
    networkId: 196 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: `https://rpc.xlayer.tech`,
    symbol: 'OKB',
    scanAddressPath: (hash: string) => `https://www.okx.com/web3/explorer/xlayer/address/${hash}`,
    scanTxPath: (hash: string) => `https://www.okx.com/web3/explorer/xlayer/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://www.okx.com/web3/explorer/xlayer/token/${hash}`,
  },
  5000: {
    // TODO: fix this before going live
    ...NETWORK_CONFIG_DEFAULT,
    name: 'Mantle',
    id: 'mantle' as const,
    hex: '0x1388',
    icon: RCMantleLogo,
    imageBaseUrl: `${CURVE_IMAGE_ASSETS_BASE_PATH}/images/assets/`,
    networkId: 5000 as const,
    orgUIPath: '',
    rpcUrlConnectWallet: `https://rpc.mantle.xyz`,
    symbol: 'MNT',
    scanAddressPath: (hash: string) => `https://mantlescan.xyz/address/${hash}`,
    scanTxPath: (hash: string) => `https://mantlescan.xyz/tx/${hash}`,
    scanTokenPath: (hash: string) => `https://mantlescan.xyz/token/${hash}`,
  },
}
