import { t } from '@evm-ui/lib/i18n'
import { TooltipDescription, TooltipItem, TooltipItems, TooltipWrapper } from '@evm-ui/shared/ui/TooltipComponents'
import { formatNumber } from '@evm-ui/utils'
import Typography from '@mui/material/Typography'

export const BaseRateTooltipContent = ({
  dailyRate,
  weeklyRate,
  weekly = false,
}: {
  dailyRate: number | null | undefined
  weeklyRate: number | null | undefined
  weekly?: boolean
}) => (
  <TooltipWrapper>
    <TooltipDescription
      text={t`Yield generated by the pool based on trading activity over the past ${weekly ? '7 days' : '24 hours'}. If the pool contains yield-bearing assets, their intrinsic yield is included.`}
    />
    <TooltipItems secondary>
      <TooltipItem variant="independent" title={t`Daily`}>
        {formatNumber(dailyRate, 'percent.rate')}
      </TooltipItem>
      <TooltipItem variant="independent" title={t`Weekly`}>
        {formatNumber(weeklyRate, 'percent.rate')}
      </TooltipItem>
    </TooltipItems>
    {[dailyRate, weeklyRate].some(rate => rate != null && rate < 0) && (
      <Typography variant="bodySRegular" color="warning">
        {t`Base APR can temporarily be negative when A parameter is ramped down, or crypto pools spend profit to rebalance.`}
      </Typography>
    )}
  </TooltipWrapper>
)
