import Typography from '@mui/material/Typography'
import { t } from '@ui-kit/lib/i18n'
import { TooltipDescription, TooltipItem, TooltipItems, TooltipWrapper } from '@ui-kit/shared/ui/TooltipComponents'
import { formatNumber } from '@ui-kit/utils'

export const BaseApyTooltipContent = ({
  dailyApy,
  weeklyApy,
  weekly = false,
}: {
  dailyApy: number | null | undefined
  weeklyApy: number | null | undefined
  weekly?: boolean
}) => (
  <TooltipWrapper>
    <TooltipDescription
      text={t`Annualized yield generated by the pool based on trading activity over the past ${weekly ? '7 days' : '24 hours'}. If the pool contains yield-bearing assets, their intrinsic yield is included.`}
    />
    <TooltipItems secondary>
      <TooltipItem variant="independent" title={t`Daily`}>
        {formatNumber(dailyApy, 'percent.rate')}
      </TooltipItem>
      <TooltipItem variant="independent" title={t`Weekly`}>
        {formatNumber(weeklyApy, 'percent.rate')}
      </TooltipItem>
    </TooltipItems>
    {[dailyApy, weeklyApy].some(apy => apy != null && apy < 0) && (
      <Typography variant="bodySRegular" color="warning">
        {t`Base APY can temporarily be negative when A parameter is ramped down, or crypto pools spend profit to rebalance.`}
      </Typography>
    )}
  </TooltipWrapper>
)
