import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import { t } from '@ui-kit/lib/i18n'
import { TooltipDescription, TooltipItem, TooltipItems, TooltipWrapper } from '@ui-kit/shared/ui/TooltipComponents'
import { formatNumber } from '@ui-kit/utils'

type BaseApyTooltipContentProps = {
  dailyApy: number | null | undefined
  weeklyApy: number | null | undefined
  weekly?: boolean
}

export const BaseApyTooltipContent = ({ dailyApy, weeklyApy, weekly = false }: BaseApyTooltipContentProps) => (
  <Box data-testid="pool-base-apy-tooltip-content">
    <TooltipWrapper>
      <TooltipDescription
        text={
          weekly
            ? t`Annualized yield generated by the pool based on trading activity over the past 7 days. If the pool contains yield-bearing assets, their intrinsic yield is included.`
            : t`Annualized yield generated by the pool based on trading activity over the past 24 hours. If the pool contains yield-bearing assets, their intrinsic yield is included.`
        }
      />
      <TooltipItems secondary>
        <TooltipItem variant="independent" title={t`Daily`}>
          {formatNumber(dailyApy, 'percent.rate')}
        </TooltipItem>
        <TooltipItem variant="independent" title={t`Weekly`}>
          {formatNumber(weeklyApy, 'percent.rate')}
        </TooltipItem>
      </TooltipItems>
      {[dailyApy, weeklyApy].some(apy => apy != null && apy < 0) && (
        <Typography variant="bodySRegular" color="warning">
          {t`Base APY can temporarily be negative when A parameter is ramped down, or crypto pools spend profit to rebalance.`}
        </Typography>
      )}
    </TooltipWrapper>
  </Box>
)
