import { TooltipDescription, TooltipWrapper } from '@ui/components/TooltipComponents'
import { t } from '@ui/lib/i18n'

export const BaseApyHeaderTooltipContent = ({ weekly = false }: { weekly?: boolean }) => (
  <TooltipWrapper>
    <TooltipDescription text={t`Annualized yield generated by the pool itself.`} />
    <TooltipDescription
      text={t`This APY is based on trading activity over the past ${weekly ? '7 days' : '24 hours'}.`}
    />
    <TooltipDescription text={t`If the pool contains yield-bearing assets, their intrinsic yield is included.`} />
  </TooltipWrapper>
)
