import { t } from '@ui-kit/lib/i18n'
import { TooltipDescription, TooltipWrapper } from '@ui-kit/shared/ui/TooltipComponents'

export const BaseApyHeaderTooltipContent = () => (
  <TooltipWrapper>
    <TooltipDescription text={t`Annualized yield generated by the pool itself.`} />
    <TooltipDescription text={t`The variable APY (vAPY) is based on trading activity over the past 24 hours.`} />
    <TooltipDescription text={t`If the pool contains yield-bearing assets, their intrinsic yield is included.`} />
  </TooltipWrapper>
)
