import { useRateDisplay } from '@evm-ui/hooks/useAprToApy'
import { t } from '@evm-ui/lib/i18n'
import { TooltipDescription, TooltipWrapper } from '@evm-ui/shared/ui/TooltipComponents'

export const BaseRateHeaderTooltipContent = ({ weekly = false }: { weekly?: boolean }) => {
  const rateDisplay = useRateDisplay()

  return (
    <TooltipWrapper>
      <TooltipDescription text={t`Annualized yield generated by the pool itself.`} />
      <TooltipDescription
        text={
          rateDisplay === 'apy'
            ? t`This APY is based on trading activity over the past ${weekly ? '7 days' : '24 hours'}.`
            : t`This APR is based on trading activity over the past ${weekly ? '7 days' : '24 hours'}.`
        }
      />
      <TooltipDescription text={t`If the pool contains yield-bearing assets, their intrinsic yield is included.`} />
    </TooltipWrapper>
  )
}
