import { t } from '@evm-ui/lib/i18n'
import { TooltipDescription, TooltipWrapper } from '@evm-ui/shared/ui/TooltipComponents'

export const BaseRateHeaderTooltipContent = ({ weekly = false }: { weekly?: boolean }) => (
  <TooltipWrapper>
    <TooltipDescription text={t`Yield generated by the pool itself.`} />
    <TooltipDescription
      text={t`This APR is based on trading activity over the past ${weekly ? '7 days' : '24 hours'}.`}
    />
    <TooltipDescription text={t`If the pool contains yield-bearing assets, their intrinsic yield is included.`} />
  </TooltipWrapper>
)
