name: CI
on: [push]
env:
  DO_NOT_TRACK: 1
  VERCEL_ALLOW_NODEJS_24: 1
  IBM_TELEMETRY_DISABLED: true
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
permissions:
  contents: read
jobs:
  cypress-e2e:
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox]
        count: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        include:
          - specs: 'cypress/e2e/llamalend/llamalend-markets.cy.ts'
    name: Cypress e2e llamalend ${{ matrix.browser }} ${{ matrix.count }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: npm install -g wait-on &

      - run: yarn set version stable
      - run: yarn install --immutable
      - name: Build app
        run: |
          set -o pipefail # fail tee if the main command fails
          yarn build 2>&1 | tee e2e-build-llamalend-${{ matrix.browser }}-${{ matrix.count }}.log

      - name: Start dev server
        run: yarn start 2>&1 | tee ../../e2e-dev-llamalend-${{ matrix.browser }}-${{ matrix.count }}.log &
        working-directory: apps/main

      - name: Start router api server
        run: yarn dev 2>&1 | tee ../../e2e-router-api-llamalend-${{ matrix.browser }}-${{ matrix.count }}.log &
        working-directory: apps/router-api

      - name: Start merkl api server
        run: yarn dev 2>&1 | tee ../../e2e-merkl-api-llamalend-${{ matrix.browser }}-${{ matrix.count }}.log &
        working-directory: apps/merkl-api
        env:
          MERKL_API_KEY: ${{ secrets.MERKL_API_KEY }}

      - name: e2e tests
        working-directory: tests
        run: |
          set -o pipefail # fail tee if the main command fails
          max_retries=10
          attempt=0
          while [ $attempt -lt $max_retries ]; do
              yarn run cy:run:e2e --browser ${{ matrix.browser }} --spec '${{ matrix.specs }}' 2>&1 | \
                tee ../e2e-cypress-llamalend-${{ matrix.browser }}-${{ matrix.count }}.log \
                >(grep --line-buffered --invert-match --fixed-strings 'INFO:CONSOLE' >&1) > /dev/null
              if [ $? -ne 0 ]; then
                  echo "Failed after $((attempt + 1)) attempts."
                  exit 1
              fi
              attempt=$((attempt + 1))
          done
        timeout-minutes: 60 # lower timeout than the whole job, so we can get screenshots on timeout
        env:
          ELECTRON_ENABLE_LOGGING: true # send console logs to stdout in electron browser
          NODE_ENV: test
          CYPRESS_VIDEO: ${{ matrix.browser == 'firefox' && 'false' || 'true' }} # Firefox doesn't support recording

      - name: Check runtime errors
        if: always()
        env:
          RUNTIME_ERRORS: |-
            update depth exceeded
            many re-renders
            unmounted component
            non-unique keys
            uncontrolled to controlled
            properties of undefined
            cannot destructure
            was reexported through module
            dependencies of each other
        run: |
          ! grep --ignore-case --extended-regexp "$(echo -n "$RUNTIME_ERRORS" | tr '\n' '|')" e2e-*.log

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-e2e-llamalend-${{ matrix.browser }}-${{ matrix.count }}
          path: tests/cypress/screenshots
          retention-days: 3
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: dev-server-log-llamalend-${{ matrix.browser }}-${{ matrix.count }}
          if-no-files-found: error
          path: e2e-*.log
