name: CI
on: [ push ]
env:
  DO_NOT_TRACK: 1
  VERCEL_ALLOW_NODEJS_24: 1
  IBM_TELEMETRY_DISABLED: true
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
permissions:
  contents: read
jobs:
  lint:
    name: Lint, format & typecheck
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # needed to diff yarn.lock against the base branch commit
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: yarn set version stable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn format:check
        if: always()
      - run: yarn typecheck
        if: always()
      - run: yarn check-supply-chain

  test:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: yarn set version stable
      - run: yarn install --immutable
      - run: yarn build  # make sure the build works + uploads source maps to Sentry
      - run: yarn test
        env:
          ENSO_API_KEY: ${{ secrets.ENSO_API_KEY }}

  cypress-component:
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox, electron ]
        count: [ 1, 2, 3, 4 ]
    name: Cypress component tests in ${{ matrix.browser }} ${{ matrix.count }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: yarn set version stable
      - run: yarn install --immutable
      - name: Optimize dependencies  # fix 'Failed to fetch dynamically imported module' when vite optimizes during tests
        run: yarn vite optimize --config vite.config.ts
        working-directory: tests

      - run: |
          set -o pipefail
          yarn run cy:run:component --browser ${{ matrix.browser }} 2>&1 | \
            tee ../cypress-component-${{ matrix.browser }}-${{ matrix.count }}.log \
              >(grep --line-buffered --invert-match --fixed-strings 'INFO:CONSOLE' >&1) > /dev/null
        working-directory: tests
        timeout-minutes: 8
        env:
          ELECTRON_ENABLE_LOGGING: true # send console logs to stdout in electron browser
          NODE_ENV: test

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-component-${{ matrix.browser }}-${{ matrix.count }}
          path: tests/cypress/screenshots
          retention-days: 3
          if-no-files-found: error

  cypress-component-rpc:
    name: Cypress component tests with RPC
    if: github.ref_name == 'main'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: yarn set version stable
      - run: yarn install --immutable
      - name: Optimize dependencies  # fix 'Failed to fetch dynamically imported module' when vite optimizes during tests
        run: yarn vite optimize --config vite.config.ts
        working-directory: tests

      - name: Run RPC tests
        run: |
          set -o pipefail # fail tee if the main command fails
          # rpc tests are expensive, stick to one browser
          yarn run cy:run:rpc --browser electron 2>&1 | \
            tee ../rpc-cypress.log >(grep --line-buffered --invert-match --fixed-strings 'INFO:CONSOLE' >&1) > /dev/null
        working-directory: tests
        env:
          ELECTRON_ENABLE_LOGGING: true # Electron writes console to stdout
          NODE_ENV: test
          CYPRESS_TENDERLY_ACCOUNT_SLUG: ${{ vars.TENDERLY_ACCOUNT_SLUG }}
          CYPRESS_TENDERLY_PROJECT_SLUG: ${{ vars.TENDERLY_PROJECT_SLUG }}
          CYPRESS_TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-rpc
          path: tests/cypress/screenshots
          retention-days: 3
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: rpc-cypress-log
          path: rpc-cypress.log
          retention-days: 3
          if-no-files-found: error

  cypress-e2e:
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox, electron ]
        count: [ 1 ]
        include:
          - browser: chrome
            count: 2
    name: Cypress e2e tests in ${{ matrix.browser }} ${{ matrix.count }}
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Restore cache
        uses: ./.github/actions/restore-cache
      - run: npm install -g wait-on &

      - run: yarn set version stable
      - run: yarn install --immutable
      - name: Build app
        run: |
          set -o pipefail # fail tee if the main command fails
          yarn build 2>&1 | tee e2e-build-${{ matrix.browser }}-${{ matrix.count }}.log

      - name: Start dev server
        run: yarn start 2>&1 | tee ../../e2e-dev-${{ matrix.browser }}-${{ matrix.count }}.log &
        working-directory: apps/main

      - name: Start api server
        run: yarn dev 2>&1 | tee ../../e2e-api-${{ matrix.browser }}-${{ matrix.count }}.log &
        working-directory: apps/router-api

      - name: e2e tests
        working-directory: tests
        run: |
          set -o pipefail # fail tee if the main command fails
          yarn run cy:run:e2e --browser ${{ matrix.browser }} 2>&1 | \
            tee ../e2e-cypress-${{ matrix.browser }}-${{ matrix.count }}.log \
              >(grep --line-buffered --invert-match --fixed-strings 'INFO:CONSOLE' >&1) > /dev/null
        env:
          ELECTRON_ENABLE_LOGGING: true # send console logs to stdout in electron browser
          NODE_ENV: test
          CYPRESS_VIDEO: ${{ matrix.browser == 'firefox' && 'false' || 'true' }}  # Firefox doesn't support recording

      - name: Check runtime errors
        if: always()
        env:
          RUNTIME_ERRORS: |-
            update depth exceeded
            many re-renders
            unmounted component
            non-unique keys
            uncontrolled to controlled
            properties of undefined
            cannot destructure
            was reexported through module
            dependencies of each other
        run: |
          ! grep --ignore-case --extended-regexp "$(echo -n "$RUNTIME_ERRORS" | tr '\n' '|')" e2e-*.log

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-e2e-${{ matrix.browser }}-${{ matrix.count }}
          path: tests/cypress/screenshots
          retention-days: 3
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: dev-server-log-${{ matrix.browser }}-${{ matrix.count }}
          if-no-files-found: error
          path: e2e-*.log

  notify:
    name: Notify Slack
    if: failure() && github.ref_name == 'main'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [ lint, test, cypress-e2e, cypress-component, cypress-component-rpc ]
    steps:
      - name: Send Slack alert
        run: |
          SLACK_TEXT="❌ <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|CI failed> \
          on <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}> \
          at <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${GITHUB_SHA:0:7}> \
          by <${{ github.server_url }}/${{ github.actor }}|${{ github.actor }}>"
          curl --request POST \
               --header 'Content-type: application/json' \
               --data-binary "{\"text\": \"$SLACK_TEXT\"}" \
               --url "${{ secrets.SLACK_FRONTEND_TEAM_WEBHOOK }}"
